using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;

namespace ExpandNullforge.Loot
{
    /// <summary>
    /// Makes a mod's own loot tables REAL: named tables that chest loot, creature drops and
    /// interaction rewards can point at exactly like a vanilla <c>LootTableID</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// WHY THIS WORKS, measured, not hoped. At load Core Keeper converts
    /// <c>Manager.mod.LootTable</c> — a plain managed list — into the loot blob
    /// (<c>LootTableConverter.Convert</c> chooses that list whenever the game is playing), and
    /// every roll afterwards finds its table by a LINEAR SCAN over the blob comparing ids
    /// (<c>PugDatabase.cs:504,537</c>). Nothing indexes by enum range, so an id the enum never
    /// declared is simply another value the scan can match. Appending a table with a minted id
    /// before conversion therefore needs no patch at drop time at all.
    /// </para>
    /// <para>
    /// THE ID IS MINTED FROM THE NAME, the framework's proven identity scheme (the tileset
    /// registry's): 64-bit FNV-1a folded into [1000, int.MaxValue). Vanilla's enum tops out at
    /// 723, so the floor clears it with room for years of official additions. Determinism is the
    /// point — the EDITOR can stamp the same id onto a creature's
    /// <c>DropsLootFromLootTableCD</c> at generation time without ever talking to this registry,
    /// because both sides compute it from the name alone.
    /// </para>
    /// <para>
    /// Guaranteed entries need their running <c>accumulatedDropChance</c> computed here: the game
    /// computed vanilla's while preparing the bank, strictly before mods run, and an entry left
    /// at zero reads as "never" to the roll that walks the pool
    /// (<c>PugDatabase.cs:543</c>). The weighted pool needs no such preparation — its roll sums
    /// weights fresh each time.
    /// </para>
    /// </remarks>
    public static class DimensionLootTableRegistry
    {
        /// <summary>One row of a registered table.</summary>
        public struct Entry
        {
            public string ItemObjectName;
            public float Weight;
            /// <summary>0 to 1. At 1 the entry joins the guaranteed pool.</summary>
            public float DropChance;
            public int MinAmount;
            public int MaxAmount;
            /// <summary>A vanilla biome name to confine the drop to, or empty for anywhere.</summary>
            public string OnlyInBiome;
        }

        private sealed class PendingTable
        {
            public string Name;
            public bool AllowEmptyRoll;
            public List<Entry> Entries;

            /// <summary>How many of its rows the last pass could resolve. Starts at "no pass yet".</summary>
            public int ResolvedLastPass = -1;
        }

        private static readonly List<PendingTable> Pending = new List<PendingTable>();
        private static readonly Dictionary<string, LootTableID> MintedByName =
            new Dictionary<string, LootTableID>();
        private static bool applied;

        /// <summary>The lowest id this registry will ever mint, safely past vanilla's enum.</summary>
        public const int MinCustomLootTableId = 1000;

        /// <summary>
        /// The deterministic name → id mapping. Same name ⇒ same id on every install, forever.
        /// </summary>
        /// <remarks>
        /// The 64-bit FNV-1a fold in <see cref="ExpandNullforge.Core.DimensionFnv"/>, shared with
        /// the tileset id, the biome id and the layout fingerprint. THE WALK IS SHARED AND FROZEN;
        /// THE RANGE IS THIS DOMAIN'S OWN. That is the line between them: the two lines below
        /// decide what a loot table id may be and nothing outside this file can move them, while
        /// the walk itself is one function because four copies of it is four chances for a saved id
        /// to stop matching its own name.
        /// CHANGING EITHER RENUMBERS EVERY CUSTOM LOOT TABLE — prefabs generated by older builds
        /// would point at ids no table carries any more.
        /// </remarks>
        public static int ComputeLootTableId(string name)
        {
            ulong hash = ExpandNullforge.Core.DimensionFnv.Hash(name);

            ulong range = (ulong)(int.MaxValue - MinCustomLootTableId);
            return MinCustomLootTableId + (int)(hash % range);
        }

        /// <summary>
        /// The name of the table a drop source is given when it has none of its own.
        /// </summary>
        /// <remarks>
        /// A source that nothing else gives a loot table still has to have one, or there is nowhere
        /// to put a drop that per-object custom loot cannot carry. The name is built from the
        /// source's full name so two creatures never share a table, and it goes through
        /// <see cref="ComputeLootTableId"/> like any other — so the editor can stamp the id onto the
        /// prefab without this registry ever being consulted.
        /// </remarks>
        public static string AutoTableNameFor(string sourceObjectName)
        {
            return string.IsNullOrEmpty(sourceObjectName)
                ? string.Empty
                : sourceObjectName + " drops";
        }

        /// <summary>
        /// Queues a table for creation at load. Call from the generated bootstrap; item names
        /// resolve when the game's objects exist.
        /// </summary>
        public static void Register(string tableName, bool allowEmptyRoll, IReadOnlyList<Entry> entries)
        {
            if (string.IsNullOrEmpty(tableName) || entries == null || entries.Count == 0)
            {
                return;
            }

            for (int i = 0; i < Pending.Count; i++)
            {
                if (string.Equals(Pending[i].Name, tableName, System.StringComparison.Ordinal))
                {
                    // Same name again is a replace, so a reloaded bootstrap cannot double every
                    // entry's weight by stacking a second copy of the table.
                    Pending.RemoveAt(i);
                    break;
                }
            }

            Pending.Add(new PendingTable
            {
                Name = tableName,
                AllowEmptyRoll = allowEmptyRoll,
                Entries = new List<Entry>(entries)
            });

            // A table registered after a pass has already closed the latch still has to be built.
            applied = false;
        }

        /// <summary>
        /// Whether an authored table is still waiting to be built under this id.
        /// </summary>
        /// <remarks>
        /// Asked by the drop registry before it mints a table of its own. The two prefixes are
        /// ordered so authored tables are built first, but an authored table now holds itself back
        /// while it is still resolving more of its rows — and during that window the drop registry
        /// would otherwise see a missing id, decide nothing carries it, and create a SECOND table
        /// under the same number.
        /// </remarks>
        public static bool HasQueuedTableWithId(LootTableID lootTableId)
        {
            for (int i = 0; i < Pending.Count; i++)
            {
                if (MintedByName.ContainsKey(Pending[i].Name))
                {
                    continue;
                }

                if ((LootTableID)ComputeLootTableId(Pending[i].Name) == lootTableId)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// How many custom loot tables are queued. Read by the world-load self-audit.
        /// </summary>
        /// <remarks>
        /// The audit needs it to tell two silences apart: the loot converter patch never running
        /// while nothing was queued is nothing at all, and the same patch never running while
        /// tables are queued means no custom drop will ever appear.
        /// </remarks>
        public static int QueuedTableCount
        {
            get { return Pending.Count; }
        }

        /// <summary>Clears queued tables (mod reload).</summary>
        public static void Clear()
        {
            Pending.Clear();
            MintedByName.Clear();
            Complained.Clear();
            applied = false;
        }

        /// <summary>
        /// Resolves a loot-table name the way every authoring field should: a vanilla
        /// <c>LootTableID</c> name first, then a registered custom table.
        /// </summary>
        /// <remarks>
        /// Vanilla-first is deliberate and mirrors the biome binding fix: an author writing
        /// "AncientChest" means the game's table, and minting an id for it instead would produce
        /// a table id nothing carries — loot that silently never drops.
        /// </remarks>
        public static bool TryResolve(string tableName, out LootTableID lootTableId)
        {
            lootTableId = LootTableID.Empty;
            if (string.IsNullOrEmpty(tableName))
            {
                return false;
            }

            if (System.Enum.TryParse(tableName, false, out lootTableId))
            {
                return true;
            }

            if (MintedByName.TryGetValue(tableName, out lootTableId))
            {
                return true;
            }

            // Before the converter has run (or from the editor side of a generated prefab) the
            // minted dictionary is empty, but the id is pure arithmetic on the name — so a
            // queued table still resolves, to exactly the id it will carry.
            for (int i = 0; i < Pending.Count; i++)
            {
                if (string.Equals(Pending[i].Name, tableName, System.StringComparison.Ordinal))
                {
                    lootTableId = (LootTableID)ComputeLootTableId(tableName);
                    return true;
                }
            }

            lootTableId = LootTableID.Empty;
            return false;
        }

        /// <summary>Every queued table, materialized into the game's own list. Idempotent per load.</summary>
        /// <remarks>
        /// IT USED TO SPEND ITS ONE CHANCE, the same way its sibling in
        /// <c>DimensionPortalDropRegistry</c> did. <c>applied</c> was latched at the end whatever
        /// happened, so a pass that ran while <c>API.Authoring.GetObjectID</c> could not yet answer
        /// dropped every row it could not resolve and never came back. Now a table is ticked off
        /// only once it is in the game's list, an untried one is retried on the next conversion,
        /// and the latch closes only when nothing is left. A table already in the list is
        /// recognised by name, so a retry cannot add it twice or accuse it of colliding with
        /// itself.
        /// </remarks>
        internal static void ApplyToLootTables()
        {
            if (applied || Pending.Count == 0)
            {
                return;
            }

            List<LootTable> lootTables = Manager.mod == null ? null : Manager.mod.LootTable;
            if (lootTables == null)
            {
                return;
            }

            bool everythingLanded = true;
            int addedThisPass = 0;

            for (int i = 0; i < Pending.Count; i++)
            {
                PendingTable pending = Pending[i];
                if (MintedByName.ContainsKey(pending.Name))
                {
                    // Already in the game's list from an earlier pass over the same queue.
                    continue;
                }

                LootTableID mintedId = (LootTableID)ComputeLootTableId(pending.Name);

                bool collided = false;
                for (int j = 0; j < lootTables.Count; j++)
                {
                    if (lootTables[j] != null && lootTables[j].id == mintedId)
                    {
                        // The tileset registry's law, for the same reason: probing to a free id
                        // would make the mapping depend on what else is installed. Reject loudly;
                        // renaming is the fix.
                        WarnOnce(
                            "Loot table '" + pending.Name + "' hashes to the " +
                            "same id as an already-registered table. It was NOT added — rename " +
                            "one of the two tables.");
                        collided = true;
                        break;
                    }
                }

                if (collided)
                {
                    // A name clash is not something a later pass can undo, so it is not a reason to
                    // keep coming back.
                    continue;
                }

                LootTable table = new LootTable
                {
                    id = mintedId,
                    minUniqueDrops = pending.AllowEmptyRoll ? 0 : 1,
                    maxUniqueDrops = 1,
                    dontAllowDuplicates = false,
                    lootInfos = new List<LootInfo>(),
                    guaranteedLootInfos = new List<LootInfo>()
                };

                bool everyRowResolved = true;
                for (int e = 0; e < pending.Entries.Count; e++)
                {
                    Entry source = pending.Entries[e];
                    ObjectID itemId = PugMod.API.Authoring.GetObjectID(source.ItemObjectName);
                    if (itemId == ObjectID.None)
                    {
                        // NOT ADDED YET, so the next conversion can try again. A name that never
                        // resolves says so once and the table goes in without it on the last pass;
                        // a name that is merely not ready yet is what this retry exists for.
                        everyRowResolved = false;
                        WarnOnce(
                            "Loot table '" + pending.Name + "' drops '" +
                            source.ItemObjectName + "', which is not a known object. That row " +
                            "was left out.");
                        continue;
                    }

                    int min = Mathf.Max(1, source.MinAmount);
                    LootInfo info = new LootInfo
                    {
                        objectID = itemId,

                        // THE CHANCE, CARRIED RATHER THAN THROWN AWAY. The number the author typed
                        // used to decide only whether the row was an always-drop and was then
                        // dropped on the floor, with the row going in at its own share instead. In
                        // a table that hands out one thing, one weighted row wins every roll — so
                        // a row written as "one in twenty" dropped on every single kill, and
                        // LOWERING a row's chance from 1 to 0.05 moved it out of the always-drops
                        // pool into a weighted pool of its own and took it from a third of the time
                        // to all of the time. This field is what the shaping below reads.
                        editorVisualDropChance = Mathf.Clamp01(source.DropChance) * 100f,
                        weight = Mathf.Max(0.0001f, source.Weight),
                        amount = new Pug.UnityExtensions.RangeInt
                        {
                            min = min,
                            max = Mathf.Max(min, source.MaxAmount)
                        },
                        isPartOfGuaranteedDrop = source.DropChance >= 1f
                    };

                    // Only set when asked. Biome's zero value IS "anywhere" — Biome.None = 0 — so
                    // leaving the field alone is already right, and writing a name the game does
                    // not have would land on None and read as "anywhere" rather than as the biome
                    // that was typed. The reason recorded here used to say the opposite.
                    if (!string.IsNullOrEmpty(source.OnlyInBiome) &&
                        System.Enum.TryParse(source.OnlyInBiome, false, out Biome biome))
                    {
                        info.onlyDropsInBiome = biome;
                    }

                    if (info.isPartOfGuaranteedDrop)
                    {
                        table.guaranteedLootInfos.Add(info);
                    }
                    else
                    {
                        table.lootInfos.Add(info);
                    }
                }

                int resolvedNow = table.lootInfos.Count + table.guaranteedLootInfos.Count;

                // HOLD IT BACK WHILE IT IS STILL GETTING BETTER. This runs inside database
                // conversion, and a pass that catches the object lookup mid-fill resolves fewer
                // rows than the next one will. A table added on that pass would carry the rows that
                // happened to be ready and lose the rest for the session. So it is only committed
                // once a pass stops finding more than the pass before it — which is also what makes
                // a name that will never resolve stop holding the whole table up.
                if (!everyRowResolved && resolvedNow > pending.ResolvedLastPass)
                {
                    pending.ResolvedLastPass = resolvedNow;
                    everythingLanded = false;
                    continue;
                }

                if (resolvedNow == 0)
                {
                    WarnOnce(
                        "Loot table '" + pending.Name + "' has no rows that " +
                        "resolved, so it was not added.");
                    continue;
                }

                // ONE ROLL PER POOL THAT HAS ANYTHING IN IT. A roll fills its guaranteed pick first
                // and only then fills what is left of the count (PugDatabase.GetRandomLoot), so a
                // table with an always-drop AND weighted rows that handed out one thing gave the
                // guaranteed pick the only slot and no weighted row could ever come out. Core
                // Keeper's own bank refuses that shape outright — "Not allowed to have guaranteed
                // drops in loot tables that only drops one item" (LootTableBank.OnAfterDeserialize).
                // THE SAME SHAPING THE AUTO-MINTED TABLES ALREADY GOT, and the reason this table
                // used to be the one place in the framework where "Drop Chance" did not mean a
                // chance. It fixes the roll count so every row's odds stop varying with it, turns
                // each row's chance into the share that produces it over that many rolls, and adds
                // a row of nothing for the remainder so a weighted pool is allowed to come up empty
                // — which is the only way one row at five percent can drop five percent of the time
                // rather than every time. See DimensionPortalDropRegistry.ShapeAMintedTable.
                //
                // The always-drops pool is untouched by it and still takes a roll of its own, so a
                // row at a chance of one goes on dropping every time.
                Portals.DimensionPortalDropRegistry.ShapeAMintedTable(table);

                if (pending.AllowEmptyRoll)
                {
                    table.minUniqueDrops = 0;
                }

                AccumulateGuaranteedChances(table.guaranteedLootInfos);
                lootTables.Add(table);
                MintedByName[pending.Name] = mintedId;
                addedThisPass++;
            }

            if (addedThisPass > 0)
            {
                Foundation.DimensionFrameworkLog.Info(
                    "Added " + addedThisPass +
                    " custom loot table(s) to the game's own loot bank.");
            }

            applied = everythingLanded;
        }

        /// <summary>Says a thing once per session, however many conversions run.</summary>
        /// <remarks>
        /// The pass is retried until every table lands, and a table naming a misspelling never
        /// will. Repeating the same sentence on every retry would bury the ones that matter.
        /// </remarks>
        private static void WarnOnce(string message)
        {
            if (Complained.Add(message))
            {
                Foundation.DimensionFrameworkLog.Warning(message);
            }
        }

        private static readonly HashSet<string> Complained =
            new HashSet<string>(System.StringComparer.Ordinal);

        /// <summary>
        /// The running share-of-total-weight walk the guaranteed roll reads. Without it every
        /// entry sits at zero, which the roll can never land on.
        /// </summary>
        private static void AccumulateGuaranteedChances(List<LootInfo> pool)
        {
            if (pool == null || pool.Count == 0)
            {
                return;
            }

            float totalWeight = 0f;
            for (int i = 0; i < pool.Count; i++)
            {
                totalWeight += pool[i].weight;
            }

            if (totalWeight <= 0f)
            {
                return;
            }

            float running = 0f;
            for (int i = 0; i < pool.Count; i++)
            {
                running += pool[i].weight / totalWeight;
                pool[i].accumulatedDropChance = running;
            }
        }
    }

    /// <summary>
    /// Runs at the same seam as the drop injection: the moment Core Keeper builds its loot blob
    /// from the managed list. This one goes FIRST, and that is now a decided thing rather than a
    /// hope.
    /// </summary>
    /// <remarks>
    /// <para>
    /// TABLES BEFORE DROPS. <c>DimensionPortalDropRegistry</c> looks a mob's table up by the id on
    /// its own <c>DropsLootFromLootTableCD</c> — and for a creature of this mod's own that id is a
    /// minted one, belonging to a table THIS prefix creates. Run the other way round, the drop
    /// registry would find no table, skip the drop, and latch <c>applied</c> for the session; the
    /// item would never drop and the table would sit there empty.
    /// </para>
    /// <para>
    /// Harmony sorts prefixes by priority, highest first, and orders unrelated patch classes
    /// arbitrarily when their priorities are equal — so leaving both at the default was leaving it
    /// to chance. <c>Priority.First</c> here and <c>Priority.Last</c> there settles it, the same way
    /// <c>DimensionSpawnDungeonAndScenePatch</c> and the tileset patches settle theirs.
    /// </para>
    /// </remarks>
    [HarmonyPatch(typeof(LootTableConverter), nameof(LootTableConverter.Convert))]
    internal static class DimensionLootTableConverterPatch
    {
        /// <summary>How many times this patch has actually run. Read by the world-load self-audit.</summary>
        /// <remarks>
        /// A patch that binds cleanly and never runs is its own bug class, and nothing else in the
        /// process can tell the two apart: the mod sandbox denies <c>HarmonyLib.Harmony</c>, so the
        /// framework cannot ask Harmony what it bound. One static increment is the whole of the
        /// evidence, and it costs one add on a path the game was already walking.
        /// </remarks>
        internal static int Fired;

        [HarmonyPrefix]
        [HarmonyPriority(Priority.First)]
        private static void Prefix()
        {
            Fired++;

            DimensionLootTableRegistry.ApplyToLootTables();
        }
    }
}
