using System.Collections.Generic;
using ExpandNullforge.Authoring;
using ExpandNullforge.EditorTools;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace ExpandNullforge.EditorTests
{
    /// <summary>
    /// Covers the first door — borrowing one of the game's own attacks whole.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A PRESET FAILS QUIETLY IN THREE WAYS, and none of them looks like a failure. It can name a
    /// field the framework no longer has, and silently leave that part of the attack at a default.
    /// It can land its values without turning the attack on, so the creature carries a perfect
    /// unused shot. And its numbers can be wrong — a preset whose damage is off by a factor is
    /// indistinguishable from one that is right until somebody plays it. These tests hold the first
    /// two; the third is held by the table being generated from the game's own prefabs rather than
    /// typed.
    /// </para>
    /// </remarks>
    public sealed class DimensionBorrowedAttackTests
    {
        private const string TestRoot = "Assets/NullforgeBorrowedTests";

        [SetUp]
        public void Setup()
        {
            DimensionTestScratchFolder.Ensure(TestRoot);
        }

        [TearDown]
        public void Cleanup()
        {
            DimensionTestScratchFolder.Remove(TestRoot);
        }

        // ---- the table itself ----

        [Test]
        public void TheTableCarriesAttacksFromBothKinds()
        {
            Assert.Greater(DimensionBorrowedAttacks.All.Length, 40, "the game has more than this");
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Melee").Length, 20);
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Ranged").Length, 20);
        }

        [Test]
        public void EveryPresetIsNamedInWordsAPlayerWouldRecognise()
        {
            for (int i = 0; i < DimensionBorrowedAttacks.All.Length; i++)
            {
                DimensionBorrowedAttacks.Preset preset = DimensionBorrowedAttacks.All[i];
                Assert.IsFalse(string.IsNullOrEmpty(preset.Name), "a preset with no name");
                Assert.IsFalse(
                    preset.Name.Contains("Entity"),
                    "'" + preset.Name + "' still reads like a file name, not a creature");
                Assert.IsFalse(
                    preset.Name.Contains("Authoring"),
                    "'" + preset.Name + "' names a component at an author");
                Assert.Greater(preset.Values.Length, 3, "'" + preset.Name + "' carries almost nothing");
            }
        }

        [Test]
        public void NoTwoPresetsShareAName()
        {
            HashSet<string> seen = new HashSet<string>();
            for (int i = 0; i < DimensionBorrowedAttacks.All.Length; i++)
            {
                string name = DimensionBorrowedAttacks.All[i].Name;
                Assert.IsTrue(seen.Add(name), "two presets are both called '" + name + "'");
            }
        }

        [Test]
        public void APresetCanBeFoundByTheNameItIsListedUnder()
        {
            DimensionBorrowedAttacks.Preset first = DimensionBorrowedAttacks.All[0];
            Assert.AreSame(first, DimensionBorrowedAttacks.ByName(first.Name));
            Assert.IsNull(DimensionBorrowedAttacks.ByName("nothing is called this"));
            Assert.IsNull(DimensionBorrowedAttacks.ByName(null));
        }

        // ---- pouring one in ----

        [Test]
        public void EveryValueInEveryPresetLandsInARealField()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                Assert.IsNotNull(combat, "the creature has no combat block to pour into");

                // THE TABLE HAS TO BE THERE. Every assertion below is satisfied by a table with no
                // presets in it, and the table is generated by Docs/harvest-borrowed-attacks.sh, so
                // a harvest that wrote a short file would leave this green over nothing.
                Assert.Greater(
                    DimensionBorrowedAttacks.All.Length,
                    400,
                    "The harvested attack table holds almost nothing, so nothing was poured and " +
                    "nothing was checked. The table is 469 presets and is regenerated by " +
                    "Docs/harvest-borrowed-attacks.sh.");

                List<string> lost = new List<string>();
                for (int i = 0; i < DimensionBorrowedAttacks.All.Length; i++)
                {
                    DimensionBorrowedAttackUtility.Apply(
                        combat,
                        DimensionBorrowedAttacks.All[i],
                        lost.Add);
                }

                Assert.IsEmpty(
                    lost,
                    "a preset naming a field that no longer exists loses part of the attack " +
                    "without anyone noticing:\n" + string.Join("\n", lost));
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void BorrowingAnAttackWritesTheGamesOwnNumbers()
        {
            DimensionBorrowedAttacks.Preset hydra =
                DimensionBorrowedAttacks.ByName("Desert Hydra — its close-up swing");
            Assert.IsNotNull(hydra, "the Desert Hydra's swing is one of the game's own attacks");

            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                DimensionBorrowedAttackUtility.Apply(combat, hydra, null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.AreEqual(1f, asset.Combat.MeleeWindUp, "measured off the game's own prefab");
                Assert.AreEqual(2f, asset.Combat.MeleeSwingDuration);
                Assert.AreEqual(293, asset.Combat.MeleeDamage);
                Assert.AreEqual(5f, asset.Combat.MeleeReach, "how close it closes to");
                Assert.AreEqual(3f, asset.Combat.MeleeSwingLandsAhead, "how far the swing lands");
                Assert.AreEqual(2f, asset.Combat.MeleeHitRadius);
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void BorrowingAnAttackAlsoGivesTheCreatureThatAttack()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");

                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Melee")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();
                Assert.IsTrue(
                    asset.Combat.HasMelee,
                    "values poured into a creature that never swings are values nothing reads");

                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Ranged")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();
                Assert.IsTrue(
                    asset.Combat.HasMelee,
                    "borrowing a shot must not take away the swing it already had");
                Assert.IsTrue(asset.Combat.HasRanged);
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void APouredPresetIsJustValuesAndStaysEditable()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.ByName("Desert Hydra — its close-up swing"),
                    null);

                combat.FindPropertyRelative("meleeDamage").intValue = 7;
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.AreEqual(
                    7,
                    asset.Combat.MeleeDamage,
                    "an author who changes a borrowed number must keep their change");
                Assert.AreEqual(1f, asset.Combat.MeleeWindUp, "and keep the rest of what they took");
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void ARangedPresetBringsWhatItShootsWithIt()
        {
            DimensionBorrowedAttacks.Preset[] ranged = DimensionBorrowedAttacks.OfKind("Ranged");
            int withAProjectile = 0;
            for (int i = 0; i < ranged.Length; i++)
            {
                for (int v = 0; v < ranged[i].Values.Length; v++)
                {
                    if (ranged[i].Values[v].Path == "projectileItemId" &&
                        !string.IsNullOrEmpty(ranged[i].Values[v].Text))
                    {
                        withAProjectile++;
                        break;
                    }
                }
            }

            Assert.Greater(
                withAProjectile,
                20,
                "a borrowed shot that does not say what it fires is a creature aiming at nothing");
        }

        [Test]
        public void AValueThatDoesNotFitIsReportedRatherThanDropped()
        {
            DimensionBorrowedAttacks.Preset broken = new DimensionBorrowedAttacks.Preset
            {
                Name = "a made-up attack",
                Creature = "nothing",
                Kind = "Melee",
                Values = new[]
                {
                    new DimensionBorrowedAttacks.Value("meleeDamage", "not a number"),
                    new DimensionBorrowedAttacks.Value("noSuchField", "1")
                }
            };

            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                List<string> said = new List<string>();
                int written = DimensionBorrowedAttackUtility.Apply(
                    serialized.FindProperty("combat"),
                    broken,
                    said.Add);

                Assert.AreEqual(0, written);
                Assert.AreEqual(2, said.Count, "both problems must be said out loud");
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void TheTableOffersMoreThanJustAttacks()
        {
            Assert.Greater(DimensionBorrowedAttacks.Kinds.Length, 2, "the two doors are not just attacks");
            Assert.Contains("Chase", DimensionBorrowedAttacks.Kinds);
            Assert.Contains("Wander", DimensionBorrowedAttacks.Kinds);

            for (int i = 0; i < DimensionBorrowedAttacks.Kinds.Length; i++)
            {
                string kind = DimensionBorrowedAttacks.Kinds[i];
                Assert.Greater(
                    DimensionBorrowedAttacks.OfKind(kind).Length,
                    0,
                    "'" + kind + "' is offered in the picker but has nothing behind it");
            }
        }

        [Test]
        public void BorrowingAWalkDoesNotGiveTheCreatureAnAttack()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                combat.FindPropertyRelative("attackKind").enumValueIndex =
                    (int)DimensionCreatureAttackKind.None;

                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Wander")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.IsFalse(
                    asset.Combat.HasMelee,
                    "a creature that borrowed a wander must not come away swinging");
                Assert.IsFalse(asset.Combat.HasRanged);
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void BorrowingAChaseFillsTheChaseAndNothingElse()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                int written = DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Chase")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.Greater(written, 5, "a chase is more than a couple of numbers");
                Assert.IsTrue(
                    asset.Combat.Pursuit.HasAnySetting,
                    "the framework only writes a chase when something in it was answered");
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        // ---- sounds by name ----

        [Test]
        public void EverySoundInEveryPresetTurnsBackIntoAName()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");

                DimensionBorrowedAttacks.Preset[] sounds = DimensionBorrowedAttacks.OfKind("Sounds");
                Assert.Greater(sounds.Length, 100, "the game authored sounds on this many creatures");

                List<string> lost = new List<string>();
                int resolved = 0;
                int unresolvable = 0;
                for (int i = 0; i < sounds.Length; i++)
                {
                    List<string> said = new List<string>();
                    resolved += DimensionBorrowedAttackUtility.Apply(combat, sounds[i], said.Add);
                    for (int s = 0; s < said.Count; s++)
                    {
                        if (said[s].Contains("#sfx:"))
                        {
                            unresolvable++;
                        }
                        else
                        {
                            lost.Add(said[s]);
                        }
                    }
                }

                Assert.IsEmpty(lost, "problems other than a nameless hash:\n" + string.Join("\n", lost));
                Assert.Greater(resolved, 300, "most sounds must come back as readable names");

                // The census when this was built: 6 of ~600 hashes name nothing the game ships.
                // A rise means the name harvest is missing a source, not that the game changed.
                Assert.LessOrEqual(
                    unresolvable,
                    20,
                    "too many sound hashes no longer resolve to names — the name list is incomplete");
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void ABorrowedSoundArrivesAsWordsAnAuthorCanRead()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");

                DimensionBorrowedAttacks.Preset[] sounds = DimensionBorrowedAttacks.OfKind("Sounds");
                DimensionBorrowedAttackUtility.Apply(combat, sounds[0], null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                string attack = asset.Combat.AttackSounds.AttackSoundName;
                Assert.IsFalse(
                    attack.StartsWith("#sfx:"),
                    "the marker must never survive into an authored field");
                if (attack.Length > 0)
                {
                    Assert.IsTrue(
                        DimensionSoundNames.IsAGameSound(attack),
                        "'" + attack + "' should be one of the game's own names");
                }
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void TheSoundNameTableRoundTrips()
        {
            Assert.Greater(DimensionSoundNames.All.Length, 1000);
            Assert.IsTrue(DimensionSoundNames.IsAGameSound("hydraBossBiteAnticipation"));
            Assert.IsFalse(DimensionSoundNames.IsAGameSound("notASound"));
            Assert.AreEqual(0, DimensionSoundNames.Hash(""), "blank is the game's own sound");

            int hash = DimensionSoundNames.Hash("hydraBossBiteAnticipation");
            Assert.AreEqual("hydraBossBiteAnticipation", DimensionSoundNames.NameForHash(hash));
            Assert.IsNull(DimensionSoundNames.NameForHash(123456789));
        }

        // ---- abilities: charge, jump, explode, ray ----

        [Test]
        public void TheTableNowOffersEveryKindOfAttackTheGameAuthored()
        {
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Charge").Length, 5);
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Jump").Length, 5);
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Explode").Length, 5);
            Assert.Greater(DimensionBorrowedAttacks.OfKind("Ray").Length, 0);
        }

        [Test]
        public void BorrowingAChargeAppendsAnAbilityRatherThanOverwritingOne()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");

                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Charge")[0],
                    null);
                DimensionBorrowedAttackUtility.Apply(
                    combat,
                    DimensionBorrowedAttacks.OfKind("Jump")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                DimensionCreatureAbility[] abilities = asset.Combat.Abilities;
                Assert.AreEqual(
                    2,
                    abilities.Length,
                    "a creature that borrows a charge and a leap does both");
                Assert.AreEqual(DimensionCreatureAbilityKind.ChargeAttack, abilities[0].Kind);
                Assert.AreEqual(DimensionCreatureAbilityKind.JumpAttack, abilities[1].Kind);
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void ABorrowedChargeCarriesTheGamesOwnNumbersIntoTheAbility()
        {
            DimensionBorrowedAttacks.Preset scarab =
                DimensionBorrowedAttacks.ByName("Bomb Scarab — the way it charges");
            Assert.IsNotNull(scarab, "the Bomb Scarab's charge is one of the game's own");

            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                List<string> lost = new List<string>();
                DimensionBorrowedAttackUtility.Apply(
                    serialized.FindProperty("combat"),
                    scarab,
                    lost.Add);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.IsEmpty(lost, string.Join("\n", lost));

                DimensionCreatureAbility charge = asset.Combat.Abilities[0];
                Assert.AreEqual(0.5f, charge.WindUp, "measured off the game's own prefab");
                Assert.AreEqual(8f, charge.SpeedMultiplier);
                Assert.AreEqual(3f, charge.Range);
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void EveryAbilityValueInEveryPresetLandsInARealField()
        {
            string[] kinds = { "Charge", "Jump", "Explode", "Ray" };
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                SerializedProperty combat = serialized.FindProperty("combat");
                List<string> lost = new List<string>();
                int applied = 0;
                for (int k = 0; k < kinds.Length; k++)
                {
                    DimensionBorrowedAttacks.Preset[] presets =
                        DimensionBorrowedAttacks.OfKind(kinds[k]);
                    for (int i = 0; i < presets.Length; i++)
                    {
                        DimensionBorrowedAttackUtility.Apply(combat, presets[i], lost.Add);
                        applied++;
                    }
                }

                // Four kinds asked for by name. A rename in the table answers all four with an
                // empty array, and nothing would be poured for this to find a lost field in.
                Assert.Greater(
                    applied,
                    0,
                    "None of the four ability kinds (" + string.Join(", ", kinds) + ") matched a " +
                    "preset, so nothing was poured and nothing was checked.");

                Assert.IsEmpty(lost, string.Join("\n", lost));
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }

        [Test]
        public void BorrowingARaySwitchesTheRayOn()
        {
            DimensionMobAsset asset = ScriptableObject.CreateInstance<DimensionMobAsset>();
            try
            {
                SerializedObject serialized = new SerializedObject(asset);
                DimensionBorrowedAttackUtility.Apply(
                    serialized.FindProperty("combat"),
                    DimensionBorrowedAttacks.OfKind("Ray")[0],
                    null);
                serialized.ApplyModifiedPropertiesWithoutUndo();

                Assert.IsTrue(
                    asset.Combat.MoreCombat.SweepsARay,
                    "a borrowed ray whose toggle is off is values nothing reads");
            }
            finally
            {
                Object.DestroyImmediate(asset);
            }
        }
    }
}
