using ExpandNullforge.Api;
using ExpandNullforge.Authoring;
using ExpandNullforge.Zones;
using NUnit.Framework;
using Unity.Mathematics;
using UnityEngine;

namespace ExpandNullforge.EditorTests
{
    /// <summary>
    /// Covers the rules that keep a player's world from changing shape underneath them.
    /// </summary>
    /// <remarks>
    /// Every failure in this area is silent and permanent. Core Keeper writes terrain to disk the first
    /// time a player visits somewhere, so a layout that drifts between builds does not produce an error
    /// — it produces a save where the explored half and the unexplored half were generated by different
    /// rules, and no reload will ever reconcile them. These tests are the only place that behaviour is
    /// observable before it ships.
    /// </remarks>
    public sealed class DimensionLayoutVersionTests
    {
        private DimensionLayoutTemplateAsset layout;

        [SetUp]
        public void CreateLayout()
        {
            layout = ScriptableObject.CreateInstance<DimensionLayoutTemplateAsset>();
            DimensionLayoutVersionRegistry.Clear();
            DimensionLayoutDriftPolicyRegistry.Clear();
        }

        [TearDown]
        public void DestroyLayout()
        {
            if (layout != null)
            {
                Object.DestroyImmediate(layout);
            }

            DimensionLayoutVersionRegistry.Clear();
            DimensionLayoutDriftPolicyRegistry.Clear();
        }

        private static DimensionLayoutArchivedRegion[] Regions(params int[] extents)
        {
            DimensionLayoutArchivedRegion[] regions = new DimensionLayoutArchivedRegion[extents.Length];
            for (int i = 0; i < extents.Length; i++)
            {
                regions[i] = new DimensionLayoutArchivedRegion(
                    "r" + i,
                    "biome" + i,
                    "zone" + i,
                    "Region " + i,
                    new DimensionBounds(
                        new int2(-extents[i], -extents[i]),
                        new int2(extents[i], extents[i])),
                    i);
            }

            return regions;
        }

        // ---- fingerprint ----

        [Test]
        public void AnUneditedLayoutKeepsTheSameShapeCode()
        {
            string first = DimensionLayoutFingerprint.Compute(layout);
            string second = DimensionLayoutFingerprint.Compute(layout);
            Assert.AreEqual(first, second, "Computing the fingerprint twice must not change it.");
        }

        [Test]
        public void MovingARingChangesTheShapeCode()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string before = DimensionLayoutFingerprint.Compute(layout);

            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 4);
            string after = DimensionLayoutFingerprint.Compute(layout);

            Assert.AreNotEqual(
                before,
                after,
                "A ring that reaches further makes a different world, so the shape code must differ.");
        }

        [Test]
        public void AFingerprintFromNothingIsStillAUsableValue()
        {
            // Callers compare fingerprints without null checks; a null here would be an exception at
            // world load, which costs the whole dimension over a layout nobody assigned.
            Assert.AreEqual(DimensionLayoutFingerprint.Empty, DimensionLayoutFingerprint.Compute(null));
        }

        [Test]
        public void AWorldWithNoRecordedShapeIsNotReportedAsChanged()
        {
            // The state of every world made before this mechanism existed. Reporting a mismatch would
            // send an author looking for a change that nobody made.
            Assert.IsTrue(DimensionLayoutFingerprint.Matches(layout, string.Empty));
        }

        // ---- publishing ----

        [Test]
        public void PublishingRecordsTheShapeAndMakesItTheCurrentVersion()
        {
            string error;
            Assert.IsTrue(layout.TryPublishVersion(Regions(64), "now", string.Empty, out error), error);

            Assert.AreEqual(1, layout.PublishedVersions.Length);
            Assert.AreEqual(layout.LayoutVersion, layout.PublishedVersions[0].Version);
            Assert.AreEqual(layout.CurrentFingerprint, layout.PublishedVersions[0].Fingerprint);
            Assert.IsFalse(layout.HasUnpublishedChanges);
        }

        [Test]
        public void PublishingTheSameShapeTwiceIsRefused()
        {
            string error;
            Assert.IsTrue(layout.TryPublishVersion(Regions(64), "now", string.Empty, out error), error);
            Assert.IsFalse(
                layout.TryPublishVersion(Regions(64), "now", string.Empty, out error),
                "Two versions that generate identical worlds are two things to reason about where " +
                "there is only one.");
            Assert.IsNotEmpty(error);
        }

        [Test]
        public void PublishingNothingIsRefusedRatherThanStoredAsAnEmptyWorld()
        {
            string error;
            Assert.IsFalse(
                layout.TryPublishVersion(new DimensionLayoutArchivedRegion[0], "now", string.Empty, out error));
            Assert.IsFalse(
                layout.TryPublishVersion(null, "now", string.Empty, out error),
                "A world pinned to an empty layout would generate no biomes at all.");
        }

        [Test]
        public void EditingAfterPublishingIsReportedAsUnpublished()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);

            string error;
            Assert.IsTrue(layout.TryPublishVersion(Regions(128), "now", string.Empty, out error), error);
            Assert.IsFalse(layout.HasUnpublishedChanges);

            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 8);
            Assert.IsTrue(
                layout.HasUnpublishedChanges,
                "The layout no longer matches the version it claims to be, which is exactly the state " +
                "that makes two builds disagree.");
        }

        [Test]
        public void EachPublishGetsItsOwnVersionNumberAndKeepsTheOldOne()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string error;
            layout.TryPublishVersion(Regions(128), "t1", string.Empty, out error);
            int first = layout.LayoutVersion;

            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 8);
            layout.TryPublishVersion(Regions(512), "t2", string.Empty, out error);
            int second = layout.LayoutVersion;

            Assert.Greater(second, first);
            Assert.AreEqual(2, layout.PublishedVersions.Length);
            Assert.IsNotNull(
                layout.FindPublishedVersion(first),
                "The older version must survive, or nothing pinned to it can be generated.");
        }

        // ---- the pin decision ----

        [Test]
        public void ANewWorldTakesTheCurrentLayoutAndIsStamped()
        {
            string error;
            layout.TryPublishVersion(Regions(64), "now", string.Empty, out error);

            DimensionLayoutPinDecision decision =
                DimensionLayoutPinResolver.Resolve(layout, 0, string.Empty);

            Assert.AreEqual(DimensionLayoutPinOutcome.StampedNewWorld, decision.Outcome);
            Assert.AreEqual(layout.LayoutVersion, decision.VersionToUse);
            Assert.AreEqual(layout.CurrentFingerprint, decision.FingerprintToStamp);
            Assert.IsFalse(decision.UsesArchivedLayout);
            Assert.IsEmpty(decision.Message, "Nothing has gone wrong, so nothing should be said.");
        }

        [Test]
        public void AWorldMadeByTheCurrentLayoutIsLeftAlone()
        {
            string error;
            layout.TryPublishVersion(Regions(64), "now", string.Empty, out error);

            DimensionLayoutPinDecision decision = DimensionLayoutPinResolver.Resolve(
                layout,
                layout.LayoutVersion,
                layout.CurrentFingerprint);

            Assert.AreEqual(DimensionLayoutPinOutcome.Unchanged, decision.Outcome);
            Assert.IsFalse(decision.UsesArchivedLayout);
            Assert.IsEmpty(decision.Message);
        }

        [Test]
        public void AnOlderWorldGeneratesFromTheVersionThatMadeIt()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string error;
            layout.TryPublishVersion(Regions(128), "t1", string.Empty, out error);
            int oldVersion = layout.LayoutVersion;
            string oldFingerprint = layout.CurrentFingerprint;

            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 8);
            layout.TryPublishVersion(Regions(512), "t2", string.Empty, out error);

            DimensionLayoutPinDecision decision =
                DimensionLayoutPinResolver.Resolve(layout, oldVersion, oldFingerprint);

            Assert.AreEqual(DimensionLayoutPinOutcome.PinnedToArchivedVersion, decision.Outcome);
            Assert.AreEqual(oldVersion, decision.VersionToUse);
            Assert.IsTrue(decision.UsesArchivedLayout);
            Assert.IsEmpty(
                decision.Message,
                "Pinning worked exactly as intended, so there is nothing to warn anyone about.");
        }

        [Test]
        public void AnOlderWorldAdoptsTheNewLayoutWhenTheAuthorAsksForThatAndIsToldWhy()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string error;
            layout.TryPublishVersion(Regions(128), "t1", string.Empty, out error);
            int oldVersion = layout.LayoutVersion;
            string oldFingerprint = layout.CurrentFingerprint;

            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 8);
            layout.TryPublishVersion(Regions(512), "t2", string.Empty, out error);

            DimensionLayoutPinDecision decision = DimensionLayoutPinResolver.Resolve(
                layout.LayoutVersion,
                layout.CurrentFingerprint,
                DimensionLayoutDriftPolicy.AlwaysUseLatest,
                oldVersion,
                oldFingerprint,
                true,
                oldFingerprint);

            Assert.AreEqual(DimensionLayoutPinOutcome.AdoptedLatest, decision.Outcome);
            Assert.AreEqual(layout.LayoutVersion, decision.VersionToUse);
            Assert.IsFalse(decision.UsesArchivedLayout);
            Assert.IsNotEmpty(
                decision.Message,
                "Accepting a seam in a player's save is a real cost and must be said out loud.");
        }

        [Test]
        public void AWorldFromAVersionThatWasNeverPublishedSaysSoRatherThanPretending()
        {
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string error;
            layout.TryPublishVersion(Regions(128), "t1", string.Empty, out error);

            DimensionLayoutPinDecision decision =
                DimensionLayoutPinResolver.Resolve(layout, 99, "deadbeef");

            Assert.AreEqual(DimensionLayoutPinOutcome.ArchiveMissing, decision.Outcome);
            Assert.AreEqual(layout.LayoutVersion, decision.VersionToUse);
            Assert.IsFalse(decision.UsesArchivedLayout);
            Assert.IsNotEmpty(decision.Message);
        }

        [Test]
        public void AWorldMadeFromAnUnpublishedEditFallsBackToThePublishedCopyAndSaysSo()
        {
            // The nastiest real case: the author edited the layout, built, played, then published. The
            // world on disk matches nothing that was ever recorded.
            layout.ApplyRadialRingsPreset("core", "outer", "core", 64, 2);
            string error;
            layout.TryPublishVersion(Regions(128), "t1", string.Empty, out error);

            DimensionLayoutPinDecision decision =
                DimensionLayoutPinResolver.Resolve(layout, layout.LayoutVersion, "0badc0de");

            Assert.AreEqual(DimensionLayoutPinOutcome.PinnedToArchivedVersion, decision.Outcome);
            Assert.IsTrue(decision.UsesArchivedLayout);
            Assert.IsNotEmpty(
                decision.Message,
                "The closest honest answer is still not the world the player has, so say so.");
        }

        [Test]
        public void ALayoutWithNoVersionsAtAllStillProducesAUsableDecision()
        {
            DimensionLayoutPinDecision decision =
                DimensionLayoutPinResolver.Resolve(null, 3, "abcd1234");

            Assert.AreEqual(DimensionLayoutPinOutcome.StampedNewWorld, decision.Outcome);
            Assert.IsFalse(decision.UsesArchivedLayout);
        }

        // ---- runtime registry ----

        [Test]
        public void TheRuntimeRegistryFindsAVersionByNumberAndIgnoresOthers()
        {
            DimensionLayoutVersionRegistry.RegisterCurrent("dim", 2, "aaaa1111");
            DimensionLayoutVersionRegistry.RegisterVersion("dim", 1, "1111aaaa", new DimensionZoneDefinition[0]);
            DimensionLayoutVersionRegistry.RegisterVersion("dim", 2, "aaaa1111", new DimensionZoneDefinition[0]);

            Assert.AreEqual(2, DimensionLayoutVersionRegistry.GetCurrentVersion("dim"));
            Assert.AreEqual("aaaa1111", DimensionLayoutVersionRegistry.GetCurrentFingerprint("dim"));
            Assert.IsNotNull(DimensionLayoutVersionRegistry.FindVersion("dim", 1));
            Assert.IsNull(DimensionLayoutVersionRegistry.FindVersion("dim", 3));
            Assert.IsNull(DimensionLayoutVersionRegistry.FindVersion("other", 1));
        }

        [Test]
        public void RegisteringAVersionTwiceReplacesItRatherThanStackingIt()
        {
            // Load order must not decide which copy wins, and a duplicate would make FindVersion's
            // answer depend on which mod happened to register first.
            DimensionLayoutVersionRegistry.RegisterVersion(
                "dim", 1, "first", new[] { Zone("a") });
            DimensionLayoutVersionRegistry.RegisterVersion(
                "dim", 1, "second", new[] { Zone("a"), Zone("b") });

            DimensionLayoutVersionRecord record = DimensionLayoutVersionRegistry.FindVersion("dim", 1);
            Assert.AreEqual("second", record.Fingerprint);
            Assert.AreEqual(2, record.Zones.Count);
        }

        [Test]
        public void ADimensionWithNoRecordedPolicyKeepsExistingWorlds()
        {
            // The conservative default matters: a missing policy must never be the reason a player's
            // world quietly changes shape.
            Assert.AreEqual(
                DimensionLayoutDriftPolicy.KeepExistingWorlds,
                DimensionLayoutDriftPolicyRegistry.GetPolicy("never-registered"));
        }

        private static DimensionZoneDefinition Zone(string id)
        {
            return new DimensionZoneDefinition(
                id,
                id,
                "dim",
                new DimensionBounds(new int2(-8, -8), new int2(8, 8)),
                id,
                0,
                true);
        }
    }
}
