using System.Collections.Generic;
using ExpandNullforge.Api;
using Unity.Mathematics;
using UnityEngine;

namespace ExpandNullforge.Authoring
{
    public sealed class DimensionTemplateStarterRequest
    {
        public string DimensionId = "mod.dimension";
        public string DimensionDisplayName = "Custom Dimension";
        public string DimensionDescription = "Starter dimension generated by the Dimension Framework authoring helpers.";
        public string ContentPackId = "mod.dimension.pack";
        public string ContentPackDisplayName = "Custom Dimension Pack";
        public string ContentPackVersion = "1.0.0";
        public string ContentPackAuthor = string.Empty;
        public string[] DependencyContentPackIds = new string[0];
        public string BiomeId = "starter";
        public string BiomeDisplayName = "Starter Biome";
        public string ZoneId = "starter";
        public string EnvironmentProfileId = string.Empty;
        public string PaletteId = string.Empty;
        public string GenerationProfileId = string.Empty;
        public string TerrainTableId = string.Empty;
        public string TerrainPassId = string.Empty;
        public string TerrainGenerationProviderId = string.Empty;
        public Vector2Int AbsoluteOrigin = new Vector2Int(10000, 10000);
        public int GenerationVersion = 1;
        public int HalfSizeTiles = 64;
        public int ReservedShellPaddingTiles = 256;
        public Color BiomeMapColor = new Color(0.25f, 0.45f, 0.55f, 1f);
        public string FloorResourceKey = "starter.floor";
        public string WallResourceKey = "starter.wall";
        public string LiquidResourceKey = string.Empty;
        public string OreResourceKey = string.Empty;
        public string ObjectResourceKey = string.Empty;
        public DimensionSpaceKind SpaceKind = DimensionSpaceKind.PocketWorld;
        public DimensionCapabilityFlags Capabilities = DimensionTemplateStarterFactory.DefaultCapabilities;

        public static DimensionTemplateStarterRequest CreateDefault(
            string dimensionId,
            string dimensionDisplayName)
        {
            DimensionTemplateStarterRequest request = new DimensionTemplateStarterRequest();
            request.DimensionId = string.IsNullOrEmpty(dimensionId) ? request.DimensionId : dimensionId;
            request.DimensionDisplayName = string.IsNullOrEmpty(dimensionDisplayName)
                ? request.DimensionDisplayName
                : dimensionDisplayName;
            request.ContentPackId = request.DimensionId + ".pack";
            request.ContentPackDisplayName = request.DimensionDisplayName + " Pack";
            request.BiomeId = request.DimensionId + ".starter";
            request.BiomeDisplayName = request.DimensionDisplayName + " Starter Biome";
            request.TerrainGenerationProviderId = DimensionGenerationProviderIds.SafePlatform;
            return request;
        }
    }

    public sealed class DimensionTemplateStarterGraph
    {
        public DimensionTemplateStarterGraph(
            DimensionTemplateAsset dimension,
            DimensionLayoutTemplateAsset layout,
            BiomeTemplateAsset biome,
            EnvironmentProfileTemplateAsset environmentProfile,
            BiomePaletteTemplateAsset palette,
            BiomeGenerationProfileAsset generationProfile,
            GenerationPassTemplateAsset[] generationPasses,
            GenerationTableTemplateAsset[] generationTables,
            DimensionBounds playableLocalBounds,
            DimensionBounds reservedLocalBounds)
            : this(
                dimension,
                layout,
                biome,
                environmentProfile,
                palette,
                generationProfile,
                generationPasses,
                generationTables,
                playableLocalBounds,
                reservedLocalBounds,
                new DimensionPortalAccessRuleAsset[0])
        {
        }

        public DimensionTemplateStarterGraph(
            DimensionTemplateAsset dimension,
            DimensionLayoutTemplateAsset layout,
            BiomeTemplateAsset biome,
            EnvironmentProfileTemplateAsset environmentProfile,
            BiomePaletteTemplateAsset palette,
            BiomeGenerationProfileAsset generationProfile,
            GenerationPassTemplateAsset[] generationPasses,
            GenerationTableTemplateAsset[] generationTables,
            DimensionBounds playableLocalBounds,
            DimensionBounds reservedLocalBounds,
            DimensionPortalAccessRuleAsset[] portalAccessRules)
        {
            Dimension = dimension;
            Layout = layout;
            Biome = biome;
            EnvironmentProfile = environmentProfile;
            Palette = palette;
            GenerationProfile = generationProfile;
            GenerationPasses = generationPasses ?? new GenerationPassTemplateAsset[0];
            GenerationTables = generationTables ?? new GenerationTableTemplateAsset[0];
            PlayableLocalBounds = playableLocalBounds;
            ReservedLocalBounds = reservedLocalBounds;
            PortalAccessRules = portalAccessRules ?? new DimensionPortalAccessRuleAsset[0];
        }

        public DimensionTemplateAsset Dimension { get; private set; }

        public DimensionLayoutTemplateAsset Layout { get; private set; }

        public BiomeTemplateAsset Biome { get; private set; }

        public EnvironmentProfileTemplateAsset EnvironmentProfile { get; private set; }

        public BiomePaletteTemplateAsset Palette { get; private set; }

        public BiomeGenerationProfileAsset GenerationProfile { get; private set; }

        public GenerationPassTemplateAsset[] GenerationPasses { get; private set; }

        public GenerationTableTemplateAsset[] GenerationTables { get; private set; }

        public DimensionPortalAccessRuleAsset[] PortalAccessRules { get; private set; }

        public DimensionPortalVisualProfileAsset PortalVisualProfile
        {
            get
            {
                return Dimension == null
                    ? null
                    : Dimension.PortalVisualProfile;
            }
        }

        public DimensionBounds PlayableLocalBounds { get; private set; }

        public DimensionBounds ReservedLocalBounds { get; private set; }
    }

    public static class DimensionTemplateStarterFactory
    {
        public const int MaxReservedShellPaddingTiles = 5000;

        public const DimensionCapabilityFlags DefaultCapabilities =
            DimensionCapabilityFlags.LocalCoordinates |
            DimensionCapabilityFlags.AbsoluteCoordinates |
            DimensionCapabilityFlags.PlayerContext |
            DimensionCapabilityFlags.PlayerTravel |
            DimensionCapabilityFlags.Portals |
            DimensionCapabilityFlags.Map |
            DimensionCapabilityFlags.Minimap |
            DimensionCapabilityFlags.Markers |
            DimensionCapabilityFlags.Generation |
            DimensionCapabilityFlags.AreaLoading |
            DimensionCapabilityFlags.SimulationLoading |
            DimensionCapabilityFlags.Persistence |
            DimensionCapabilityFlags.Multiplayer |
            DimensionCapabilityFlags.Zones |
            DimensionCapabilityFlags.CustomBiomeLookup |
            DimensionCapabilityFlags.CoordinateInterop;

        public static DimensionTemplateStarterGraph CreateSingleBiomeStarter(
            DimensionTemplateStarterRequest request)
        {
            DimensionTemplateStarterRequest resolved = request ?? new DimensionTemplateStarterRequest();

            string dimensionId = ResolveId(resolved.DimensionId, "mod.dimension");
            string dimensionDisplayName = ResolveDisplayName(resolved.DimensionDisplayName, dimensionId);
            string contentPackId = ResolveId(resolved.ContentPackId, dimensionId + ".pack");
            string contentPackDisplayName = ResolveDisplayName(resolved.ContentPackDisplayName, dimensionDisplayName + " Pack");
            string biomeId = ResolveId(resolved.BiomeId, dimensionId + ".starter");
            string biomeDisplayName = ResolveDisplayName(resolved.BiomeDisplayName, biomeId);
            string zoneId = ResolveId(resolved.ZoneId, biomeId + ".zone");
            string environmentProfileId = ResolveId(resolved.EnvironmentProfileId, biomeId + ".environment");
            string paletteId = ResolveId(resolved.PaletteId, biomeId + ".palette");
            string generationProfileId = ResolveId(resolved.GenerationProfileId, biomeId + ".generation");
            string terrainTableId = ResolveId(resolved.TerrainTableId, "terrain");
            string terrainPassId = ResolveId(resolved.TerrainPassId, "terrain-pass");
            int halfSizeTiles = Mathf.Max(1, resolved.HalfSizeTiles);
            int shellPaddingTiles = Mathf.Clamp(
                resolved.ReservedShellPaddingTiles,
                0,
                MaxReservedShellPaddingTiles);

            DimensionBounds playableLocalBounds = new DimensionBounds(
                new int2(-halfSizeTiles, -halfSizeTiles),
                new int2(halfSizeTiles, halfSizeTiles));
            DimensionBounds reservedLocalBounds = ExpandBounds(playableLocalBounds, shellPaddingTiles);

            EnvironmentProfileTemplateAsset environmentProfile =
                ScriptableObject.CreateInstance<EnvironmentProfileTemplateAsset>();
            environmentProfile.name = environmentProfileId;
            environmentProfile.ConfigureIdentity(
                environmentProfileId,
                biomeDisplayName + " Environment",
                zoneId,
                0,
                true);
            environmentProfile.ConfigureMapColor(resolved.BiomeMapColor);

            BiomePaletteTemplateAsset palette =
                ScriptableObject.CreateInstance<BiomePaletteTemplateAsset>();
            palette.name = paletteId;
            palette.ConfigureIdentity(
                paletteId,
                biomeDisplayName + " Palette",
                paletteId,
                0,
                true,
                "Starter palette generated by the Dimension Framework authoring helpers.");
            palette.ApplySemanticTerrainPreset(
                resolved.FloorResourceKey,
                resolved.WallResourceKey,
                resolved.LiquidResourceKey,
                resolved.OreResourceKey,
                resolved.ObjectResourceKey);

            GenerationTableTemplateAsset terrainTable = CreateTerrainTable(
                terrainTableId,
                biomeId,
                resolved.FloorResourceKey,
                resolved.WallResourceKey,
                resolved.LiquidResourceKey,
                resolved.OreResourceKey,
                resolved.ObjectResourceKey);
            GenerationTableTemplateAsset[] generationTables =
                terrainTable == null
                    ? new GenerationTableTemplateAsset[0]
                    : new[] { terrainTable };

            GenerationPassTemplateAsset[] generationPasses =
                string.IsNullOrEmpty(resolved.TerrainGenerationProviderId)
                    ? new GenerationPassTemplateAsset[0]
                    : new[] { CreateTerrainPass(terrainPassId, resolved.TerrainGenerationProviderId, playableLocalBounds) };

            BiomeGenerationProfileAsset generationProfile =
                ScriptableObject.CreateInstance<BiomeGenerationProfileAsset>();
            generationProfile.name = generationProfileId;
            generationProfile.ConfigureIdentity(
                generationProfileId,
                biomeDisplayName + " Generation",
                "Starter generation profile generated by the Dimension Framework authoring helpers.");
            generationProfile.SetGenerationPasses(generationPasses);
            generationProfile.SetTerrainTables(generationTables);

            BiomeTemplateAsset biome = ScriptableObject.CreateInstance<BiomeTemplateAsset>();
            biome.name = biomeId;
            biome.ConfigureIdentity(
                biomeId,
                biomeDisplayName,
                resolved.BiomeMapColor,
                0,
                true);
            biome.ApplyFallbackLocalBounds(
                new Vector2Int(playableLocalBounds.Min.x, playableLocalBounds.Min.y),
                new Vector2Int(playableLocalBounds.MaxExclusive.x, playableLocalBounds.MaxExclusive.y));
            biome.ApplySemanticTerrainPreset(
                ToSingleValueArray(resolved.FloorResourceKey),
                ToSingleValueArray(resolved.WallResourceKey),
                ToSingleValueArray(resolved.OreResourceKey),
                ToSingleValueArray(resolved.LiquidResourceKey),
                true);
            biome.ConfigureEnvironmentProfile(environmentProfile.ProfileId, environmentProfile);
            biome.ConfigurePalette(palette.PaletteId, palette);
            biome.ConfigureGenerationProfile(generationProfile);
            biome.SetContentPresets(new BiomeContentPresetAsset[0]);
            biome.SetScenePool(new SceneTemplateAsset[0]);
            biome.SetResourceNodes(new ResourceNodeTemplateAsset[0]);
            biome.SetSpawnRules(new SpawnRuleTemplateAsset[0]);
            biome.SetGenerationTables(new GenerationTableTemplateAsset[0]);

            DimensionLayoutTemplateAsset layout =
                ScriptableObject.CreateInstance<DimensionLayoutTemplateAsset>();
            layout.name = dimensionId + ".layout";
            layout.ApplySingleBiomeSquarePreset(biomeId, zoneId, halfSizeTiles);

            DimensionPortalAccessRuleAsset[] portalAccessRules =
                CreateDefaultPortalAccessRules(dimensionId, dimensionDisplayName);

            DimensionPortalVisualProfileAsset portalVisualProfile =
                ScriptableObject.CreateInstance<DimensionPortalVisualProfileAsset>();
            portalVisualProfile.name = "PortalVisualProfile";

            DimensionTemplateAsset dimension = ScriptableObject.CreateInstance<DimensionTemplateAsset>();
            dimension.name = dimensionId;
            dimension.ConfigureIdentity(
                dimensionId,
                dimensionDisplayName,
                resolved.DimensionDescription ?? string.Empty,
                contentPackId,
                contentPackDisplayName,
                string.IsNullOrEmpty(resolved.ContentPackVersion) ? "1.0.0" : resolved.ContentPackVersion,
                resolved.ContentPackAuthor ?? string.Empty,
                1,
                resolved.SpaceKind,
                resolved.Capabilities == DimensionCapabilityFlags.None
                    ? DefaultCapabilities
                    : resolved.Capabilities);
            dimension.SetDependencyContentPackIds(resolved.DependencyContentPackIds);
            dimension.ConfigurePlacement(resolved.AbsoluteOrigin, Mathf.Max(1, resolved.GenerationVersion));
            dimension.ApplyReservedLocalBounds(reservedLocalBounds);
            dimension.SetLayoutTemplate(layout);
            dimension.SetEnvironmentProfiles(new EnvironmentProfileTemplateAsset[0]);
            dimension.SetBiomes(new[] { biome });
            dimension.SetGlobalScenes(new SceneTemplateAsset[0]);
            dimension.SetGlobalResourceNodes(new ResourceNodeTemplateAsset[0]);
            dimension.SetGlobalItems(new DimensionItemAsset[0]);
            dimension.SetGlobalRecipes(new DimensionRecipeAsset[0]);
            dimension.SetGlobalWorkbenches(new DimensionWorkbenchAsset[0]);
            dimension.SetGlobalLootTables(new DimensionLootTableAsset[0]);
            dimension.SetGlobalAnimals(new DimensionAnimalAsset[0]);
            dimension.SetGlobalCritters(new DimensionCritterAsset[0]);
            dimension.SetGlobalMobs(new DimensionMobAsset[0]);
            dimension.SetGlobalBosses(new DimensionBossAsset[0]);
            dimension.SetGlobalSpawnRules(new SpawnRuleTemplateAsset[0]);
            dimension.SetGlobalGenerationPasses(new GenerationPassTemplateAsset[0]);
            dimension.SetGlobalGenerationTables(new GenerationTableTemplateAsset[0]);
            dimension.SetPortalAccessRules(portalAccessRules);
            dimension.ConfigurePortalAppearance(30.0f, portalVisualProfile);

            return new DimensionTemplateStarterGraph(
                dimension,
                layout,
                biome,
                environmentProfile,
                palette,
                generationProfile,
                generationPasses,
                generationTables,
                playableLocalBounds,
                reservedLocalBounds,
                portalAccessRules);
        }

        private static DimensionPortalAccessRuleAsset[] CreateDefaultPortalAccessRules(
            string dimensionId,
            string dimensionDisplayName)
        {
            string safeDimensionId = ResolveId(dimensionId, "mod.dimension");
            string safeDisplayName = ResolveDisplayName(dimensionDisplayName, safeDimensionId);

            DimensionPortalAccessRuleAsset entryRule =
                ScriptableObject.CreateInstance<DimensionPortalAccessRuleAsset>();
            entryRule.name = safeDimensionId + ".portal.entry";
            entryRule.Configure(
                safeDimensionId + ".portal.entry.rule",
                safeDimensionId + ".portal.entry",
                safeDimensionId + ".portal.entry.presentation",
                safeDisplayName + " Portal",
                DimensionIds.Overworld,
                Vector2.zero,
                safeDimensionId,
                Vector2.zero,
                DimensionPortalAccessKind.PlacedPortal,
                DimensionPortalActivationMode.VanillaCooldown,
                2.0f,
                true,
                true,
                "Enter " + safeDisplayName,
                "The portal is still activating.",
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                true,
                new DimensionPortalRequiredItemTemplate[0]);

            DimensionPortalAccessRuleAsset returnRule =
                ScriptableObject.CreateInstance<DimensionPortalAccessRuleAsset>();
            returnRule.name = safeDimensionId + ".portal.return";
            returnRule.Configure(
                safeDimensionId + ".portal.return.rule",
                safeDimensionId + ".portal.return",
                safeDimensionId + ".portal.return.presentation",
                safeDisplayName + " Return Portal",
                safeDimensionId,
                Vector2.zero,
                DimensionIds.Overworld,
                Vector2.zero,
                DimensionPortalAccessKind.GeneratedReturnPortal,
                DimensionPortalActivationMode.AlwaysAvailable,
                0.0f,
                false,
                true,
                "Return to the Core",
                string.Empty,
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                true,
                new DimensionPortalRequiredItemTemplate[0]);

            return new[] { entryRule, returnRule };
        }

        private static GenerationPassTemplateAsset CreateTerrainPass(
            string passId,
            string providerId,
            DimensionBounds localBounds)
        {
            GenerationPassTemplateAsset pass =
                ScriptableObject.CreateInstance<GenerationPassTemplateAsset>();
            pass.name = passId;
            pass.ConfigureIdentity(
                passId,
                "Terrain",
                DimensionGenerationPassPhase.Terrain,
                providerId,
                0,
                true);
            pass.ClearExplicitLocalBounds();
            return pass;
        }

        private static GenerationTableTemplateAsset CreateTerrainTable(
            string tableId,
            string biomeId,
            string floorResourceKey,
            string wallResourceKey,
            string liquidResourceKey,
            string oreResourceKey,
            string objectResourceKey)
        {
            List<GenerationTableEntryTemplate> entries = new List<GenerationTableEntryTemplate>();
            AddTableEntry(entries, "floor", floorResourceKey, "tile", 100, 1, 1);
            AddTableEntry(entries, "wall", wallResourceKey, "tile", 100, 1, 1);
            AddTableEntry(entries, "liquid", liquidResourceKey, "tile", 20, 1, 1);
            AddTableEntry(entries, "ore", oreResourceKey, "tile", 10, 1, 1);
            AddTableEntry(entries, "object", objectResourceKey, "object", 10, 1, 1);

            if (entries.Count == 0)
            {
                return null;
            }

            GenerationTableTemplateAsset table =
                ScriptableObject.CreateInstance<GenerationTableTemplateAsset>();
            table.name = tableId;
            table.ConfigureIdentity(
                tableId,
                "Terrain Choices",
                DimensionGenerationTableKind.Terrain,
                biomeId,
                0,
                true,
                "Starter terrain table generated by the Dimension Framework authoring helpers.");
            table.SetEntries(entries);
            return table;
        }

        private static void AddTableEntry(
            List<GenerationTableEntryTemplate> entries,
            string entryId,
            string subjectId,
            string subjectKind,
            int weight,
            int minCount,
            int maxCount)
        {
            if (entries == null || string.IsNullOrEmpty(subjectId))
            {
                return;
            }

            entries.Add(new GenerationTableEntryTemplate(
                entryId,
                subjectId,
                subjectKind,
                weight,
                minCount,
                maxCount,
                0,
                true,
                string.Empty));
        }

        private static string ResolveId(string value, string fallback)
        {
            if (!string.IsNullOrEmpty(value))
            {
                return value;
            }

            return fallback ?? string.Empty;
        }

        private static string ResolveDisplayName(string value, string fallback)
        {
            if (!string.IsNullOrEmpty(value))
            {
                return value;
            }

            return fallback ?? string.Empty;
        }

        private static DimensionBounds ExpandBounds(DimensionBounds bounds, int padding)
        {
            int safePadding = Mathf.Max(0, padding);
            return new DimensionBounds(
                new int2(bounds.Min.x - safePadding, bounds.Min.y - safePadding),
                new int2(bounds.MaxExclusive.x + safePadding, bounds.MaxExclusive.y + safePadding));
        }

        private static string[] ToSingleValueArray(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return new string[0];
            }

            return new[] { value };
        }
    }
}
