using System.Collections.Generic;
using ExpandNullforge.Api;
using Unity.Mathematics;
using UnityEngine;

namespace ExpandNullforge.Authoring
{
    public sealed class DimensionTemplateStarterRequest
    {
        public string DimensionId = "mod.dimension";
        public string DimensionDisplayName = "Custom Dimension";
        public string DimensionDescription = "Starter dimension generated by the Dimension Framework authoring helpers.";
        public string ContentPackId = "mod.dimension.pack";
        public string ContentPackDisplayName = "Custom Dimension Pack";
        public string ContentPackVersion = "1.0.0";
        public string ContentPackAuthor = string.Empty;
        public string[] DependencyContentPackIds = new string[0];
        public string BiomeId = "starter";
        public string BiomeDisplayName = "Starter Biome";
        public string ZoneId = "starter";
        public string TerrainPassId = string.Empty;
        public string TerrainGenerationProviderId = string.Empty;
        // Must clear the protected ±5000 overworld band by the dimension's half-extent; an origin
        // exactly at 5000 makes the playable bounds straddle it and registration fails. See
        // DimensionTemplateCreationWizard.AbsoluteOriginX/Y.
        public Vector2Int AbsoluteOrigin = new Vector2Int(0, 7000);
        public int GenerationVersion = 1;
        public int HalfSizeTiles = 64;
        public int ReservedShellPaddingTiles = 256;
        public Color BiomeMapColor = new Color(0.25f, 0.45f, 0.55f, 1f);
        public string FloorResourceKey = "starter.floor";
        public string WallResourceKey = "starter.wall";
        public string LiquidResourceKey = string.Empty;
        public string OreResourceKey = string.Empty;
        public string ObjectResourceKey = string.Empty;
        public DimensionType Type = DimensionType.World;
        public DimensionCapabilityFlags Capabilities = DimensionTemplateStarterFactory.DefaultCapabilities;

        public static DimensionTemplateStarterRequest CreateDefault(
            string dimensionId,
            string dimensionDisplayName)
        {
            DimensionTemplateStarterRequest request = new DimensionTemplateStarterRequest();
            request.DimensionId = string.IsNullOrEmpty(dimensionId) ? request.DimensionId : dimensionId;
            request.DimensionDisplayName = string.IsNullOrEmpty(dimensionDisplayName)
                ? request.DimensionDisplayName
                : dimensionDisplayName;
            request.ContentPackId = request.DimensionId + ".pack";
            request.ContentPackDisplayName = request.DimensionDisplayName + " Pack";
            request.BiomeId = request.DimensionId + ".starter";
            request.BiomeDisplayName = "Starter Biome";
            request.TerrainGenerationProviderId = DimensionGenerationProviderIds.SafePlatform;
            return request;
        }
    }

    public sealed class DimensionTemplateStarterGraph
    {
        public DimensionTemplateStarterGraph(
            DimensionTemplateAsset dimension,
            DimensionLayoutTemplateAsset layout,
            BiomeTemplateAsset biome,
            GenerationPassTemplateAsset[] generationPasses,
            DimensionBounds playableLocalBounds,
            DimensionBounds reservedLocalBounds)
            : this(
                dimension,
                layout,
                biome,
                generationPasses,
                playableLocalBounds,
                reservedLocalBounds,
                new DimensionPortalAccessRuleAsset[0])
        {
        }

        public DimensionTemplateStarterGraph(
            DimensionTemplateAsset dimension,
            DimensionLayoutTemplateAsset layout,
            BiomeTemplateAsset biome,
            GenerationPassTemplateAsset[] generationPasses,
            DimensionBounds playableLocalBounds,
            DimensionBounds reservedLocalBounds,
            DimensionPortalAccessRuleAsset[] portalAccessRules)
        {
            Dimension = dimension;
            Layout = layout;
            Biome = biome;
            GenerationPasses = generationPasses ?? new GenerationPassTemplateAsset[0];
            PlayableLocalBounds = playableLocalBounds;
            ReservedLocalBounds = reservedLocalBounds;
            PortalAccessRules = portalAccessRules ?? new DimensionPortalAccessRuleAsset[0];
        }

        public DimensionTemplateAsset Dimension { get; private set; }

        public DimensionLayoutTemplateAsset Layout { get; private set; }

        public BiomeTemplateAsset Biome { get; private set; }

        /// <summary>
        /// The generation steps the starter biome runs, in order.
        /// </summary>
        /// <remarks>
        /// The biome owns its passes, so this list and <c>Biome.GenerationPasses</c> are the same
        /// list. Handing them out twice — here and again inside a separate Biome Generation Profile
        /// asset the biome points at — is what makes the two disagree.
        /// </remarks>
        public GenerationPassTemplateAsset[] GenerationPasses { get; private set; }

        public DimensionPortalAccessRuleAsset[] PortalAccessRules { get; private set; }

        public DimensionPortalVisualProfileAsset PortalVisualProfile
        {
            get
            {
                return Dimension == null
                    ? null
                    : Dimension.PortalVisualProfile;
            }
        }

        public DimensionBounds PlayableLocalBounds { get; private set; }

        public DimensionBounds ReservedLocalBounds { get; private set; }
    }

    public static class DimensionTemplateStarterFactory
    {
        public const int MaxReservedShellPaddingTiles = 5000;

        public const DimensionCapabilityFlags DefaultCapabilities =
            DimensionCapabilityFlags.LocalCoordinates |
            DimensionCapabilityFlags.AbsoluteCoordinates |
            DimensionCapabilityFlags.PlayerContext |
            DimensionCapabilityFlags.PlayerTravel |
            DimensionCapabilityFlags.Portals |
            DimensionCapabilityFlags.Map |
            DimensionCapabilityFlags.Minimap |
            DimensionCapabilityFlags.Markers |
            DimensionCapabilityFlags.Generation |
            DimensionCapabilityFlags.AreaLoading |
            DimensionCapabilityFlags.SimulationLoading |
            DimensionCapabilityFlags.Persistence |
            DimensionCapabilityFlags.Multiplayer |
            DimensionCapabilityFlags.Zones |
            DimensionCapabilityFlags.CustomBiomeLookup |
            DimensionCapabilityFlags.CoordinateInterop;

        public static DimensionTemplateStarterGraph CreateSingleBiomeStarter(
            DimensionTemplateStarterRequest request)
        {
            DimensionTemplateStarterRequest resolved = request ?? new DimensionTemplateStarterRequest();

            string dimensionId = ResolveId(resolved.DimensionId, "mod.dimension");
            string dimensionDisplayName = ResolveDisplayName(resolved.DimensionDisplayName, dimensionId);
            string contentPackId = ResolveId(resolved.ContentPackId, dimensionId + ".pack");
            string contentPackDisplayName = ResolveDisplayName(resolved.ContentPackDisplayName, dimensionDisplayName + " Pack");
            string biomeId = ResolveId(resolved.BiomeId, dimensionId + ".starter");
            string biomeDisplayName = ResolveDisplayName(resolved.BiomeDisplayName, biomeId);
            string zoneId = ResolveId(resolved.ZoneId, biomeId + ".zone");
            string terrainPassId = ResolveId(resolved.TerrainPassId, "terrain-pass");
            int halfSizeTiles = Mathf.Max(1, resolved.HalfSizeTiles);
            int shellPaddingTiles = Mathf.Clamp(
                resolved.ReservedShellPaddingTiles,
                0,
                MaxReservedShellPaddingTiles);

            DimensionBounds playableLocalBounds = new DimensionBounds(
                new int2(-halfSizeTiles, -halfSizeTiles),
                new int2(halfSizeTiles, halfSizeTiles));
            DimensionBounds reservedLocalBounds = ExpandBounds(playableLocalBounds, shellPaddingTiles);

            GenerationPassTemplateAsset[] generationPasses =
                string.IsNullOrEmpty(resolved.TerrainGenerationProviderId)
                    ? new GenerationPassTemplateAsset[0]
                    : new[] { CreateTerrainPass(terrainPassId, resolved.TerrainGenerationProviderId, playableLocalBounds) };

            BiomeTemplateAsset biome = ScriptableObject.CreateInstance<BiomeTemplateAsset>();
            biome.name = biomeId;
            biome.ConfigureIdentity(
                biomeId,
                biomeDisplayName,
                resolved.BiomeMapColor,
                0,
                true);
            biome.ApplyFallbackLocalBounds(
                new Vector2Int(playableLocalBounds.Min.x, playableLocalBounds.Min.y),
                new Vector2Int(playableLocalBounds.MaxExclusive.x, playableLocalBounds.MaxExclusive.y));
            biome.ApplySemanticTerrainPreset(
                ToSingleValueArray(resolved.FloorResourceKey),
                ToSingleValueArray(resolved.WallResourceKey),
                ToSingleValueArray(resolved.OreResourceKey),
                true);
            biome.SetGenerationPasses(generationPasses);
            biome.SetScenePool(new SceneTemplateAsset[0]);

            DimensionLayoutTemplateAsset layout =
                ScriptableObject.CreateInstance<DimensionLayoutTemplateAsset>();
            layout.name = dimensionId + ".layout";
            layout.ApplySingleBiomeSquarePreset(biomeId, zoneId, halfSizeTiles);

            DimensionPortalAccessRuleAsset[] portalAccessRules =
                CreateDefaultPortalAccessRules(dimensionId, dimensionDisplayName);

            DimensionPortalVisualProfileAsset portalVisualProfile =
                ScriptableObject.CreateInstance<DimensionPortalVisualProfileAsset>();
            portalVisualProfile.name = "PortalVisualProfile";

            DimensionTemplateAsset dimension = ScriptableObject.CreateInstance<DimensionTemplateAsset>();
            dimension.name = dimensionId;
            dimension.ConfigureIdentity(
                dimensionId,
                dimensionDisplayName,
                resolved.DimensionDescription ?? string.Empty,
                contentPackId,
                contentPackDisplayName,
                string.IsNullOrEmpty(resolved.ContentPackVersion) ? "1.0.0" : resolved.ContentPackVersion,
                resolved.ContentPackAuthor ?? string.Empty,
                1,
                resolved.Type,
                resolved.Capabilities == DimensionCapabilityFlags.None
                    ? DefaultCapabilities
                    : resolved.Capabilities);
            dimension.SetDependencyContentPackIds(resolved.DependencyContentPackIds);
            dimension.ConfigurePlacement(resolved.AbsoluteOrigin, Mathf.Max(1, resolved.GenerationVersion));
            dimension.ApplyReservedLocalBounds(reservedLocalBounds);
            dimension.SetLayoutTemplate(layout);
            dimension.SetBiomes(new[] { biome });
            dimension.SetGlobalScenes(new SceneTemplateAsset[0]);
            dimension.SetGlobalItems(new DimensionItemAsset[0]);
            dimension.SetGlobalRecipes(new DimensionRecipeAsset[0]);
            dimension.SetGlobalWorkbenches(new DimensionWorkbenchAsset[0]);
            dimension.SetGlobalLootTables(new DimensionLootTableAsset[0]);
            dimension.SetGlobalAnimals(new DimensionAnimalAsset[0]);
            dimension.SetGlobalCritters(new DimensionCritterAsset[0]);
            dimension.SetGlobalGameSetups(new DimensionGameSetupAsset[0]);
            dimension.SetGlobalConditions(new DimensionConditionAsset[0]);
            dimension.SetGlobalMobs(new DimensionMobAsset[0]);
            dimension.SetGlobalBosses(new DimensionBossAsset[0]);
            dimension.SetGlobalGenerationPasses(new GenerationPassTemplateAsset[0]);
            dimension.SetPortalAccessRules(portalAccessRules);
            dimension.ConfigurePortalAppearance(30.0f, portalVisualProfile);

            return new DimensionTemplateStarterGraph(
                dimension,
                layout,
                biome,
                generationPasses,
                playableLocalBounds,
                reservedLocalBounds,
                portalAccessRules);
        }

        private static DimensionPortalAccessRuleAsset[] CreateDefaultPortalAccessRules(
            string dimensionId,
            string dimensionDisplayName)
        {
            return new[]
            {
                CreatePortalAccessRule(
                    DimensionPortalAccessKind.PlacedPortal, dimensionId, dimensionDisplayName),
                CreatePortalAccessRule(
                    DimensionPortalAccessKind.InventoryItem, dimensionId, dimensionDisplayName),
                CreatePortalAccessRule(
                    DimensionPortalAccessKind.GeneratedReturnPortal, dimensionId, dimensionDisplayName),
            };
        }

        /// <summary>
        /// One portal access rule of the given kind, born with the defaults a new dimension gets.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The one place those defaults live. A dimension gets exactly one effective rule per kind —
        /// the generator takes the FIRST enabled match — so both the starter that seeds all three
        /// and the Portal Studio's repair button, which replaces a single missing one, have to agree
        /// about what a rule of that kind is. Two copies of these numbers would drift, and the
        /// symptom would be a repaired portal that behaves unlike a fresh one.
        /// </para>
        /// <para>
        /// The returned asset is a loose <see cref="ScriptableObject"/>: whoever asked for it owns
        /// saving it to disk and adding it to a dimension.
        /// </para>
        /// </remarks>
        public static DimensionPortalAccessRuleAsset CreatePortalAccessRule(
            DimensionPortalAccessKind kind,
            string dimensionId,
            string dimensionDisplayName)
        {
            string safeDimensionId = ResolveId(dimensionId, "mod.dimension");
            string safeDisplayName = ResolveDisplayName(dimensionDisplayName, safeDimensionId);
            switch (kind)
            {
                case DimensionPortalAccessKind.InventoryItem:
                    return CreateDefaultItemPortalRule(safeDimensionId, safeDisplayName);
                case DimensionPortalAccessKind.GeneratedReturnPortal:
                    return CreateDefaultReturnPortalRule(safeDimensionId, safeDisplayName);
                default:
                    return CreateDefaultPlacedPortalRule(safeDimensionId, safeDisplayName);
            }
        }

        private static DimensionPortalAccessRuleAsset CreateDefaultPlacedPortalRule(
            string safeDimensionId,
            string safeDisplayName)
        {
            DimensionPortalAccessRuleAsset entryRule =
                ScriptableObject.CreateInstance<DimensionPortalAccessRuleAsset>();
            entryRule.name = safeDimensionId + ".portal.entry";
            entryRule.Configure(
                safeDimensionId + ".portal.entry.rule",
                safeDimensionId + ".portal.entry",
                safeDimensionId + ".portal.entry.presentation",
                safeDisplayName + " Portal",
                DimensionIds.Overworld,
                Vector2.zero,
                safeDimensionId,
                Vector2.zero,
                DimensionPortalAccessKind.PlacedPortal,
                DimensionPortalActivationMode.VanillaCooldown,
                2.0f,
                true,
                true,
                "Enter " + safeDisplayName,
                "The portal is still activating.",
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                true,
                new DimensionPortalRequiredItemTemplate[0]);
            // V1 (user-accessible) defaults: craftable at the workbench, not world-generated or
            // droppable unless the modder opts in.
            entryRule.ConfigureVersionSettings(
                true,
                string.Empty,
                false,
                false,
                new DimensionPortalDropTarget[0],
                string.Empty,
                10f);
            return entryRule;
        }

        // V2 (instantaneous item portal): disabled by default so V1 is the out-of-the-box way
        // in, but fully seeded so the modder can enable it with one toggle. Its custom item id
        // is auto-created by the generator.
        private static DimensionPortalAccessRuleAsset CreateDefaultItemPortalRule(
            string safeDimensionId,
            string safeDisplayName)
        {
            DimensionPortalAccessRuleAsset itemRule =
                ScriptableObject.CreateInstance<DimensionPortalAccessRuleAsset>();
            itemRule.name = safeDimensionId + ".portal.item";
            itemRule.Configure(
                safeDimensionId + ".portal.item.rule",
                safeDimensionId + ".portal.item",
                safeDimensionId + ".portal.item.presentation",
                safeDisplayName + " Portal (Item)",
                DimensionIds.Overworld,
                Vector2.zero,
                safeDimensionId,
                Vector2.zero,
                DimensionPortalAccessKind.InventoryItem,
                DimensionPortalActivationMode.VanillaCooldown,
                2.0f,
                true,
                true,
                "Enter " + safeDisplayName,
                "The portal is still activating.",
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                false,
                new DimensionPortalRequiredItemTemplate[0]);
            itemRule.ConfigureVersionSettings(
                true,
                string.Empty,
                false,
                false,
                new DimensionPortalDropTarget[0],
                safeDimensionId + ".portal.item.object",
                10f);
            return itemRule;
        }

        private static DimensionPortalAccessRuleAsset CreateDefaultReturnPortalRule(
            string safeDimensionId,
            string safeDisplayName)
        {
            DimensionPortalAccessRuleAsset returnRule =
                ScriptableObject.CreateInstance<DimensionPortalAccessRuleAsset>();
            returnRule.name = safeDimensionId + ".portal.return";
            returnRule.Configure(
                safeDimensionId + ".portal.return.rule",
                safeDimensionId + ".portal.return",
                safeDimensionId + ".portal.return.presentation",
                safeDisplayName + " Return Portal",
                safeDimensionId,
                Vector2.zero,
                DimensionIds.Overworld,
                Vector2.zero,
                DimensionPortalAccessKind.GeneratedReturnPortal,
                DimensionPortalActivationMode.AlwaysAvailable,
                0.0f,
                false,
                true,
                "Return to the Core",
                string.Empty,
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                true,
                new DimensionPortalRequiredItemTemplate[0]);
            returnRule.ConfigureVersionSettings(
                false,
                string.Empty,
                false,
                false,
                new DimensionPortalDropTarget[0],
                string.Empty,
                10f);
            return returnRule;
        }

        private static GenerationPassTemplateAsset CreateTerrainPass(
            string passId,
            string providerId,
            DimensionBounds localBounds)
        {
            GenerationPassTemplateAsset pass =
                ScriptableObject.CreateInstance<GenerationPassTemplateAsset>();
            pass.name = passId;
            pass.ConfigureIdentity(
                passId,
                "Terrain",
                DimensionGenerationPassPhase.Terrain,
                providerId,
                0,
                true);
            pass.ClearExplicitLocalBounds();
            return pass;
        }

        private static string ResolveId(string value, string fallback)
        {
            if (!string.IsNullOrEmpty(value))
            {
                return value;
            }

            return fallback ?? string.Empty;
        }

        private static string ResolveDisplayName(string value, string fallback)
        {
            if (!string.IsNullOrEmpty(value))
            {
                return value;
            }

            return fallback ?? string.Empty;
        }

        private static DimensionBounds ExpandBounds(DimensionBounds bounds, int padding)
        {
            int safePadding = Mathf.Max(0, padding);
            return new DimensionBounds(
                new int2(bounds.Min.x - safePadding, bounds.Min.y - safePadding),
                new int2(bounds.MaxExclusive.x + safePadding, bounds.MaxExclusive.y + safePadding));
        }

        private static string[] ToSingleValueArray(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return new string[0];
            }

            return new[] { value };
        }
    }
}
