namespace ExpandNullforge.Authoring
{
    /// <summary>
    /// What the framework does when a save was generated by a layout version that is no longer current.
    /// </summary>
    /// <remarks>
    /// There is no universally right answer, which is why this is a choice rather than a rule. A mod
    /// still in development wants every reload to show the newest layout. A mod people are playing
    /// wants their worlds left alone. The only genuinely wrong behaviour is doing either one silently.
    /// </remarks>
    public enum DimensionLayoutDriftPolicy
    {
        /// <summary>
        /// The world keeps the layout it was made with, generating from the archived version.
        /// </summary>
        /// <remarks>
        /// The right default for anything players have already started. Terrain in Core Keeper is
        /// created the first time someone walks there, so a world that changes layout mid-save does not
        /// regenerate — it grows a seam where old terrain meets new.
        /// </remarks>
        KeepExistingWorlds = 0,

        /// <summary>
        /// Existing saves adopt the current layout, and the mismatch is reported once.
        /// </summary>
        /// <remarks>
        /// For iterating: reload the same test world and see the change immediately. Shipping with this
        /// is a decision to accept seams in players' saves, which is why it says so out loud.
        /// </remarks>
        AlwaysUseLatest = 1
    }
}
