using UnityEngine;

namespace ExpandNullforge.Authoring
{
    [CreateAssetMenu(menuName = "Dimensions API/Dimension Layout Template")]
    public sealed class DimensionLayoutTemplateAsset : ScriptableObject
    {
        [SerializeField] private string layoutId = "layout";
        [SerializeField] private string displayName = "Dimension Layout";
        [SerializeField] private DimensionLayoutKind layoutKind = DimensionLayoutKind.ManualRegions;
        [SerializeField] private DimensionLayoutRegionDefinition[] regions = new DimensionLayoutRegionDefinition[0];
        [SerializeField] private Vector2Int gridLocalMin = new Vector2Int(-64, -64);
        [SerializeField] private Vector2Int gridCellSize = new Vector2Int(64, 64);
        [SerializeField] private DimensionLayoutGridCellDefinition[] gridCells =
            new DimensionLayoutGridCellDefinition[0];
        // Kept, and deliberately not shown anywhere. Nothing reads it but a guard and the layout
        // fingerprint, and the fingerprint is why it stays: it is what tells a saved world whether
        // its layout has been reshaped, so dropping a line out of that hash would re-shape every
        // pin that has ever been taken, all at once, for an integer nothing acts on.
        [HideInInspector]
        [SerializeField] private int radialBandSizeTiles = 64;
        [SerializeField] private DimensionLayoutRadialRingDefinition[] radialRings =
            new DimensionLayoutRadialRingDefinition[0];
        [SerializeField] private Texture2D biomeMask;
        [SerializeField] private DimensionLayoutMaskBiomeDefinition[] maskBiomeMappings =
            new DimensionLayoutMaskBiomeDefinition[0];
        [SerializeField] private Vector2Int maskLocalMin = new Vector2Int(-64, -64);
        [SerializeField] private Vector2Int tilesPerMaskPixel = new Vector2Int(16, 16);
        [SerializeField] private int maskAlphaThreshold = 8;
        [SerializeField] private string notes = string.Empty;

        [Tooltip("Bumped each time you publish a layout. Worlds remember which version made them.")]
        [SerializeField] private int layoutVersion = 1;

        [Tooltip("What to do when a save was generated by a layout version that is no longer current.")]
        [SerializeField] private DimensionLayoutDriftPolicy driftPolicy =
            DimensionLayoutDriftPolicy.KeepExistingWorlds;

        [SerializeField] private DimensionLayoutArchiveEntry[] publishedVersions =
            new DimensionLayoutArchiveEntry[0];

        // The painted map, as a Newtonsoft-serialized DimensionTileMapSnapshot — the same reason
        // the runtime manifest stores it that way: Unity's JsonUtility returns empty arrays for
        // mod-defined element types in Core Keeper's recompiled-mod runtime, and Newtonsoft does
        // not. It lives HERE rather than only on the generated runtime manifest because this is
        // authoring truth and that is a build artifact; export copies it forward.
        [HideInInspector]
        [SerializeField] private string paintedTileMapJson = string.Empty;

        [System.NonSerialized] private DimensionTileMapModel cachedPaintedTileMap;
        [System.NonSerialized] private bool paintedTileMapCacheValid;

        public string LayoutId
        {
            get { return layoutId ?? string.Empty; }
        }

        public string DisplayName
        {
            get { return displayName ?? string.Empty; }
        }

        public DimensionLayoutKind LayoutKind
        {
            get { return layoutKind; }
        }

        public DimensionLayoutRegionDefinition[] Regions
        {
            get { return regions ?? new DimensionLayoutRegionDefinition[0]; }
        }

        public Vector2Int GridLocalMin
        {
            get { return gridLocalMin; }
        }

        public Vector2Int GridCellSize
        {
            get { return gridCellSize; }
        }

        public DimensionLayoutGridCellDefinition[] GridCells
        {
            get { return gridCells ?? new DimensionLayoutGridCellDefinition[0]; }
        }

        public int RadialBandSizeTiles
        {
            get { return radialBandSizeTiles < 1 ? 1 : radialBandSizeTiles; }
        }

        public DimensionLayoutRadialRingDefinition[] RadialRings
        {
            get { return radialRings ?? new DimensionLayoutRadialRingDefinition[0]; }
        }

        public Texture2D BiomeMask
        {
            get { return biomeMask; }
        }

        public DimensionLayoutMaskBiomeDefinition[] MaskBiomeMappings
        {
            get { return maskBiomeMappings ?? new DimensionLayoutMaskBiomeDefinition[0]; }
        }

        public Vector2Int MaskLocalMin
        {
            get { return maskLocalMin; }
        }

        public Vector2Int TilesPerMaskPixel
        {
            get { return tilesPerMaskPixel; }
        }

        public int MaskAlphaThreshold
        {
            get { return maskAlphaThreshold < 0 ? 0 : maskAlphaThreshold > 255 ? 255 : maskAlphaThreshold; }
        }

        public string Notes
        {
            get { return notes ?? string.Empty; }
        }

        /// <summary>
        /// The version number a world generated right now would be stamped with.
        /// </summary>
        /// <remarks>
        /// Bumped by publishing rather than typed, because the number is only meaningful when an
        /// archived copy of that version exists to go with it.
        /// </remarks>
        public int LayoutVersion
        {
            get { return layoutVersion < 1 ? 1 : layoutVersion; }
        }

        /// <summary>What happens to a save whose layout version is no longer the current one.</summary>
        public DimensionLayoutDriftPolicy DriftPolicy
        {
            get { return driftPolicy; }
        }

        /// <summary>Every layout version published so far, oldest first.</summary>
        public DimensionLayoutArchiveEntry[] PublishedVersions
        {
            get { return publishedVersions ?? new DimensionLayoutArchiveEntry[0]; }
        }

        /// <summary>
        /// The map the creator painted for this dimension, or null when they have not painted one.
        /// </summary>
        /// <remarks>
        /// Deserialized once and cached, the same shape the runtime manifest uses, because the
        /// paint canvas asks for this on every repaint and parsing a 256 x 256 snapshot per frame
        /// is not something a canvas can afford.
        /// </remarks>
        public DimensionTileMapModel PaintedTileMap
        {
            get
            {
                if (!paintedTileMapCacheValid)
                {
                    cachedPaintedTileMap = string.IsNullOrEmpty(paintedTileMapJson)
                        ? null
                        : DimensionTileMapModel.FromSnapshot(
                            Newtonsoft.Json.JsonConvert.DeserializeObject<DimensionTileMapSnapshot>(
                                paintedTileMapJson));
                    paintedTileMapCacheValid = true;
                }

                return cachedPaintedTileMap;
            }
        }

        /// <summary>True when a map has been painted and something is actually on it.</summary>
        public bool HasPaintedTileMap
        {
            get
            {
                DimensionTileMapModel map = PaintedTileMap;
                return map != null && map.PaintedTileCount() > 0;
            }
        }

        /// <summary>Records the painted map. Written only by the Map page's Paint tab.</summary>
        public void SetPaintedTileMap(DimensionTileMapModel map)
        {
            paintedTileMapJson = map == null
                ? string.Empty
                : Newtonsoft.Json.JsonConvert.SerializeObject(map.ToSnapshot());
            cachedPaintedTileMap = map;
            paintedTileMapCacheValid = true;
        }

        /// <summary>The fingerprint of the layout as it stands right now.</summary>
        public string CurrentFingerprint
        {
            get { return DimensionLayoutFingerprint.Compute(this); }
        }

        /// <summary>
        /// Whether the layout has been edited since the version it claims to be was published.
        /// </summary>
        /// <remarks>
        /// This is the state that matters most and is the easiest to end up in by accident: the author
        /// nudges a ring, builds, and every existing save now generates new terrain that does not match
        /// the terrain it already has. A layout that has never been published is not "changed" — there
        /// is nothing yet to differ from.
        /// </remarks>
        public bool HasUnpublishedChanges
        {
            get
            {
                DimensionLayoutArchiveEntry published = FindPublishedVersion(LayoutVersion);
                if (published == null)
                {
                    return PublishedVersions.Length > 0;
                }

                return !string.Equals(
                    published.Fingerprint,
                    CurrentFingerprint,
                    System.StringComparison.OrdinalIgnoreCase);
            }
        }

        /// <summary>The archived copy of a version, or null when that version was never published.</summary>
        public DimensionLayoutArchiveEntry FindPublishedVersion(int version)
        {
            DimensionLayoutArchiveEntry[] entries = PublishedVersions;
            for (int i = 0; i < entries.Length; i++)
            {
                if (entries[i] != null && entries[i].Version == version)
                {
                    return entries[i];
                }
            }

            return null;
        }

        /// <summary>
        /// Records the current layout as a new version and makes that version current.
        /// </summary>
        /// <remarks>
        /// Publishing the same shape twice is refused rather than made a no-op with a new number: two
        /// versions that generate identical worlds give an author two things to reason about where
        /// there is only one, and every save pinned to either behaves the same anyway.
        /// </remarks>
        public bool TryPublishVersion(
            DimensionLayoutArchivedRegion[] compiledRegions,
            string publishedUtc,
            string publishNotes,
            out string error)
        {
            if (compiledRegions == null || compiledRegions.Length == 0)
            {
                error = "This layout does not currently produce any biome regions, so there is nothing to publish.";
                return false;
            }

            string fingerprint = CurrentFingerprint;
            DimensionLayoutArchiveEntry existing = FindPublishedVersion(LayoutVersion);
            if (existing != null &&
                string.Equals(existing.Fingerprint, fingerprint, System.StringComparison.OrdinalIgnoreCase))
            {
                error = "Version " + LayoutVersion + " already describes this exact layout. Change the " +
                    "layout before publishing again.";
                return false;
            }

            DimensionLayoutArchiveEntry[] entries = PublishedVersions;
            int nextVersion = LayoutVersion;
            for (int i = 0; i < entries.Length; i++)
            {
                if (entries[i] != null && entries[i].Version >= nextVersion)
                {
                    nextVersion = entries[i].Version + 1;
                }
            }

            if (existing != null)
            {
                nextVersion = System.Math.Max(nextVersion, LayoutVersion + 1);
            }

            DimensionLayoutArchiveEntry[] grown = new DimensionLayoutArchiveEntry[entries.Length + 1];
            for (int i = 0; i < entries.Length; i++)
            {
                grown[i] = entries[i];
            }

            grown[entries.Length] = new DimensionLayoutArchiveEntry(
                nextVersion,
                fingerprint,
                publishedUtc,
                publishNotes,
                compiledRegions);

            publishedVersions = grown;
            layoutVersion = nextVersion;
            error = string.Empty;
            return true;
        }

        public void ApplySingleBiomeSquarePreset(
            string biomeId,
            string zoneId,
            int halfSizeTiles)
        {
            int halfSize = NormalizeTileSize(halfSizeTiles, 8);
            layoutKind = DimensionLayoutKind.ManualRegions;
            regions = new[]
            {
                new DimensionLayoutRegionDefinition(
                    "single-biome",
                    biomeId,
                    zoneId,
                    "Single Biome",
                    new Vector2Int(-halfSize, -halfSize),
                    new Vector2Int(halfSize, halfSize),
                    0,
                    true)
            };
            gridCells = new DimensionLayoutGridCellDefinition[0];
            radialRings = new DimensionLayoutRadialRingDefinition[0];
            maskBiomeMappings = new DimensionLayoutMaskBiomeDefinition[0];
            biomeMask = null;
            notes = "Generated from the single-biome square preset.";
        }

        public void ApplyCenteredGridPreset(
            string fallbackBiomeId,
            string zoneId,
            int columns,
            int rows,
            int cellSizeTiles,
            string[] biomeIds)
        {
            int safeColumns = NormalizeTileSize(columns, 1);
            int safeRows = NormalizeTileSize(rows, 1);
            int safeCellSize = NormalizeTileSize(cellSizeTiles, 16);
            layoutKind = DimensionLayoutKind.GridRegions;
            gridCellSize = new Vector2Int(safeCellSize, safeCellSize);
            gridLocalMin = new Vector2Int(
                -((safeColumns * safeCellSize) / 2),
                -((safeRows * safeCellSize) / 2));
            regions = new DimensionLayoutRegionDefinition[0];
            gridCells = new DimensionLayoutGridCellDefinition[safeColumns * safeRows];
            radialRings = new DimensionLayoutRadialRingDefinition[0];
            maskBiomeMappings = new DimensionLayoutMaskBiomeDefinition[0];
            biomeMask = null;

            int index = 0;
            for (int y = 0; y < safeRows; y++)
            {
                for (int x = 0; x < safeColumns; x++)
                {
                    string biomeId = ResolveBiomeSlot(biomeIds, index, fallbackBiomeId);
                    gridCells[index] = new DimensionLayoutGridCellDefinition(
                        "grid-cell-" + x.ToString() + "-" + y.ToString(),
                        biomeId,
                        zoneId,
                        "Grid Cell " + x.ToString() + ", " + y.ToString(),
                        new Vector2Int(x, y),
                        new Vector2Int(1, 1),
                        0,
                        true);
                    index++;
                }
            }

            notes = "Generated from the centered-grid preset.";
        }

        public void ApplyRadialRingsPreset(
            string centerBiomeId,
            string outerBiomeId,
            string zoneId,
            int ringWidthTiles,
            int ringCount)
        {
            int safeRingWidth = NormalizeTileSize(ringWidthTiles, 16);
            int safeRingCount = NormalizeTileSize(ringCount, 1);
            layoutKind = DimensionLayoutKind.RadialRings;
            radialBandSizeTiles = safeRingWidth;
            regions = new DimensionLayoutRegionDefinition[0];
            gridCells = new DimensionLayoutGridCellDefinition[0];
            radialRings = new DimensionLayoutRadialRingDefinition[safeRingCount];
            maskBiomeMappings = new DimensionLayoutMaskBiomeDefinition[0];
            biomeMask = null;

            for (int i = 0; i < safeRingCount; i++)
            {
                int minRadius = i * safeRingWidth;
                int maxRadius = minRadius + safeRingWidth;
                string biomeId = i == 0 || string.IsNullOrEmpty(outerBiomeId)
                    ? centerBiomeId
                    : outerBiomeId;
                radialRings[i] = new DimensionLayoutRadialRingDefinition(
                    "radial-ring-" + i.ToString(),
                    biomeId,
                    zoneId,
                    i == 0 ? "Center Ring" : "Outer Ring " + i.ToString(),
                    minRadius,
                    maxRadius,
                    i,
                    true);
            }

            notes = "Generated from the radial-rings preset.";
        }

        private static int NormalizeTileSize(int value, int fallback)
        {
            if (value < 1)
            {
                return fallback < 1 ? 1 : fallback;
            }

            return value;
        }

        private static string ResolveBiomeSlot(string[] biomeIds, int index, string fallbackBiomeId)
        {
            if (biomeIds != null && index >= 0 && index < biomeIds.Length)
            {
                string biomeId = biomeIds[index] ?? string.Empty;
                if (!string.IsNullOrEmpty(biomeId))
                {
                    return biomeId;
                }
            }

            return fallbackBiomeId ?? string.Empty;
        }
    }
}
