namespace ExpandNullforge.Api
{
    public enum DimensionContentRecordKind
    {
        Any = 0,
        Dimension = 1,
        Portal = 2,
        PortalPresentation = 3,
        TravelRequirement = 4,
        TravelRequirementEvaluator = 5,
        MapLayer = 6,
        MapMarker = 7,
        Anchor = 8,
        Biome = 9,
        GenerationTable = 10,
        GenerationTableEntry = 11,
        ZoneDefinition = 12,
        ZoneProvider = 13,
        EnvironmentProfile = 14,
        Scene = 15,
        SceneTemplate = 16,
        Encounter = 17,
        ResourceNode = 18,
        SpawnRule = 19,
        WorldEvent = 20,
        ProgressFlag = 21,
        GenerationProvider = 22,
        GenerationPass = 23,
        AccessProvider = 24,
        AssetReference = 25,
        Starter = 26,
        Item = 27,
        Recipe = 28,
        Workbench = 29,
        LootTable = 30,
        Animal = 31,
        Critter = 32,
        Mob = 33,
        Boss = 34,
        SceneProp = 35,
        SceneLootContainer = 36,
        SceneSpawnPoint = 37,
        SceneTrigger = 38,
        Custom = 100
    }
}
