using System;
using System.Collections.Generic;
using PugMod;
using UnityEngine;

namespace ExpandNullforge.Objects
{
    /// <summary>
    /// The light each generated object gives off where it stands, keyed by the object name the
    /// generator gave it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// WHY A SIDE TABLE RATHER THAN SOMETHING BAKED ON THE PREFAB. It is the same reason
    /// <see cref="DimensionCraftingBenchLookRegistry"/> exists, one step further along: every
    /// generated object of one behaviour shares ONE pooled view instance, because Core Keeper pools
    /// graphical objects by component TYPE. A light baked onto the prefab is therefore one light
    /// for every crafting bench in the mod, or every chest — and which object's light it is depends
    /// on which prefab claimed the type first, so it changes when an unrelated object is added. The
    /// view has to re-derive its answer per entity, an object id is the only thing it is handed, so
    /// the answer has to be reachable from an object id.
    /// </para>
    /// <para>
    /// WHY NAMES AND NOT IDS. A mod's object has no <c>ObjectID</c> until the game hands it one
    /// while the world converts, which is long after the generated bootstrap runs. So rows arrive
    /// carrying the object NAME and the id map is built lazily, and rebuilt whenever the row count
    /// changes — the same shape the bench-look table uses, and for the same reason: there is no
    /// callback that says "mod objects now have numbers".
    /// </para>
    /// <para>
    /// AN OBJECT WITH NO ROW HAS NO LIGHT, and that is an answer rather than a gap. Containers and
    /// workbenches are generated by paths that never ask the light question, so they register
    /// nothing and <see cref="DimensionAuthoredLight.Point"/> puts the shared instance's light out
    /// for them.
    /// </para>
    /// </remarks>
    public static class DimensionEmittedLightRegistry
    {
        private static readonly List<KeyValuePair<string, DimensionEmittedLightNumbers>> Rows =
            new List<KeyValuePair<string, DimensionEmittedLightNumbers>>();

        private static readonly Dictionary<int, DimensionEmittedLightNumbers> ByObjectId =
            new Dictionary<int, DimensionEmittedLightNumbers>();

        private static int idsResolvedForCount = -1;

        /// <summary>How many objects have registered a light.</summary>
        public static int Count
        {
            get { return Rows.Count; }
        }

        /// <summary>
        /// Records the light one object gives off where it stands.
        /// </summary>
        /// <remarks>
        /// Every value is a plain number or a plain flag so the generated bootstrap can write this
        /// call without naming an editor type or a game type. They are the numbers the game runs
        /// with, not the raw answers: the brightness is already the one a flickering light settles
        /// on, and the two flicker bounds are already closed up for a light that holds still.
        /// </remarks>
        /// <param name="objectName">
        /// The object's qualified name, as the generator wrote it onto
        /// <c>ObjectAuthoring.objectName</c>.
        /// </param>
        public static void Register(
            string objectName,
            float red,
            float green,
            float blue,
            float howBright,
            float howFarItReaches,
            bool itCastsShadows,
            float atItsDimmest,
            float atItsBrightest,
            bool theFlameMoves,
            float howHighAboveTheFloor,
            float howFarFrontToBack)
        {
            if (string.IsNullOrEmpty(objectName))
            {
                return;
            }

            DimensionEmittedLightNumbers numbers = new DimensionEmittedLightNumbers(
                new Color(red, green, blue, 1f),
                howBright,
                howFarItReaches,
                itCastsShadows,
                atItsDimmest,
                atItsBrightest,
                theFlameMoves,
                howHighAboveTheFloor,
                howFarFrontToBack);

            for (int i = 0; i < Rows.Count; i++)
            {
                if (string.Equals(Rows[i].Key, objectName, StringComparison.Ordinal))
                {
                    Rows[i] = new KeyValuePair<string, DimensionEmittedLightNumbers>(
                        objectName, numbers);
                    Invalidate();
                    return;
                }
            }

            Rows.Add(new KeyValuePair<string, DimensionEmittedLightNumbers>(objectName, numbers));
            Invalidate();
        }

        /// <summary>
        /// The light this object gives off, or false when it was never given one.
        /// </summary>
        public static bool TryGet(ObjectID objectID, out DimensionEmittedLightNumbers numbers)
        {
            if (objectID == ObjectID.None || Rows.Count == 0)
            {
                numbers = default(DimensionEmittedLightNumbers);
                return false;
            }

            if (idsResolvedForCount != Rows.Count)
            {
                Rebuild();
            }

            return ByObjectId.TryGetValue((int)objectID, out numbers);
        }

        public static void Clear()
        {
            Rows.Clear();
            Invalidate();
        }

        private static void Invalidate()
        {
            ByObjectId.Clear();
            idsResolvedForCount = -1;
        }

        private static void Rebuild()
        {
            ByObjectId.Clear();
            for (int i = 0; i < Rows.Count; i++)
            {
                ObjectID id = API.Authoring.GetObjectID(Rows[i].Key);
                if (id != ObjectID.None)
                {
                    ByObjectId[(int)id] = Rows[i].Value;
                }
            }

            idsResolvedForCount = Rows.Count;
        }
    }
}
