using UnityEngine;

namespace ExpandNullforge.Objects
{
    /// <summary>
    /// The one place that knows how to put an object's own light onto the light node a framework
    /// view is holding, shared by every view that can be handed one.
    /// </summary>
    /// <remarks>
    /// <para>
    /// THIS IS THE LIGHT'S HALF OF WHAT <see cref="DimensionAuthoredBody"/> DOES FOR THE PICTURE,
    /// and for the identical reason. Every framework view is POOLED BY TYPE — Core Keeper's
    /// <c>MemoryManager.CreateModdedPrefabPool</c> ends in
    /// <c>_poolFromComponentType.TryAdd(type, prefab)</c> and <c>CreateGraphicalObjectSystem</c>
    /// asks that pool for a free component rather than instantiating the prefab — so one instance,
    /// built from one prefab, draws every object of that behaviour. An instance that lit a brazier
    /// a moment ago is handed straight to a crafting bench. A light baked onto the prefab is one
    /// light for the whole behaviour, and which object's light it is depends on which prefab
    /// registered first.
    /// </para>
    /// <para>
    /// SWITCHING THE LIGHT OFF FOR AN OBJECT THAT HAS NONE IS THE POINT OF THE CALL, exactly as
    /// switching the renderer off is the point of <c>DimensionAuthoredBody.Point</c>. Containers
    /// and workbenches are generated by paths that never ask the light question at all; leaving the
    /// previous occupant's light burning would light a chest with a forge's colour and reach, and
    /// <c>EntityMonoBehaviour.OnOccupied</c> (<c>:1117</c>) switches an assigned
    /// <c>optionalLightOptimizer</c> back on for every object drawn, so "do nothing" is not the
    /// same as "no light".
    /// </para>
    /// <para>
    /// THE GAMEOBJECT IS WHAT GOES OFF, NOT ONLY THE <c>Light</c> COMPONENT, and that is measured
    /// rather than belt-and-braces. <c>ManagedLight.OnEnable</c> assigns
    /// <c>lightToOptimize.enabled = true</c> every time its own node is activated, and
    /// <c>EntityMonoBehaviour.OnOccupied</c> activates that node on every occupy — so a light
    /// disabled by its component flag alone comes back on immediately. With the node itself
    /// inactive, <c>ManagedLight.isLightEnabled</c> is false (it reads
    /// <c>activeSelf &amp;&amp; enabled</c>), <c>SetOptimized</c> forces its fallback glow off at
    /// <c>ManagedLight.cs:109-112</c>, <c>PugLight.OnDisable</c> takes it out of
    /// <c>PugLight.instances</c>, and Unity's culling never reports it — so an unlit object costs
    /// nothing on screen and nothing against the renderer's light ceiling.
    /// </para>
    /// <para>
    /// IT IS A HELPER RATHER THAN A BASE CLASS for the same reason the body's is: each behaviour
    /// has to derive from the game's own component, so the framework's views have six different
    /// bases and nowhere to put shared code except here.
    /// </para>
    /// </remarks>
    public static class DimensionAuthoredLight
    {
        /// <summary>
        /// Gives the light node the light belonging to the object being drawn, or no light at all
        /// when that object was never given one.
        /// </summary>
        public static void Point(ManagedLight light, ObjectID objectID)
        {
            if (light == null)
            {
                return;
            }

            DimensionEmittedLightNumbers numbers;
            if (DimensionEmittedLightRegistry.TryGet(objectID, out numbers))
            {
                Show(light, numbers);
                return;
            }

            Hide(light);
        }

        /// <summary>
        /// Sets every value the game reads off a placed light, and switches it on.
        /// </summary>
        /// <remarks>
        /// <para>
        /// THE FLICKER IS TOLD BEFORE THE NODE IS ACTIVATED, and the order is load-bearing.
        /// <c>LightFlickerEffect.OnEnable</c> hands <c>minIntensity</c>, <c>maxIntensity</c> and
        /// <c>enableMovement</c> to the light manager as it is, once, and only
        /// <c>SetIntensityRange</c> pushes a later change through. Setting the fields first means
        /// one registration with the right numbers whether the node was already on or not.
        /// </para>
        /// <para>
        /// The height and the front-to-back nudge go on the <c>ManagedLight</c>'s own node, never
        /// on the light under it. <c>LightFlickerEffect.Awake</c> captures the light's local
        /// position once and moves the light around that point while it flickers, so a light that
        /// was raised by moving the light itself would be dragged back down on the first frame.
        /// The game's own six lit prefabs put the offset on the same node this does.
        /// </para>
        /// </remarks>
        public static void Show(ManagedLight light, DimensionEmittedLightNumbers numbers)
        {
            if (light == null)
            {
                return;
            }

            light.transform.localPosition = new Vector3(
                0f, numbers.HowHighAboveTheFloor, numbers.HowFarFrontToBack);

            Light bulb = light.lightToOptimize;
            if (bulb == null)
            {
                return;
            }

            bulb.color = numbers.Colour;
            bulb.intensity = numbers.HowBright;
            bulb.range = numbers.HowFarItReaches;
            bulb.shadows = numbers.ItCastsShadows ? LightShadows.Hard : LightShadows.None;

            LightFlickerEffect flicker = light.GetComponentInChildren<LightFlickerEffect>(true);
            if (flicker != null)
            {
                flicker.flickeringLight = bulb;
                flicker.enableMovement = numbers.TheFlameMoves;
                flicker.SetIntensityRange(numbers.AtItsDimmest, numbers.AtItsBrightest);
            }

            // The container is what ManagedLight.SetOptimized switches off when it decides this
            // light loses its two-tile bucket. A pooled instance can arrive still holding the
            // previous occupant's losing verdict, which would leave a lit object dark until the
            // next optimisation pass re-ran; the pass is free to switch it straight back off.
            if (light.lightContainer != null && !light.lightContainer.activeSelf)
            {
                light.lightContainer.SetActive(true);
            }

            bulb.enabled = true;
            if (!bulb.gameObject.activeSelf)
            {
                bulb.gameObject.SetActive(true);
            }
        }

        /// <summary>
        /// Leaves the light node in place and puts its light out.
        /// </summary>
        /// <remarks>
        /// The node stays because it is not this object's to remove: it belongs to the pooled
        /// instance, and the next object handed that instance may well want it. What goes off is
        /// the light itself and the glowing sprite the game swaps in for a light it has dimmed —
        /// that sprite is switched off here rather than left to the next optimisation pass, so an
        /// object that gives off no light never shows one for a frame.
        /// </remarks>
        public static void Hide(ManagedLight light)
        {
            if (light == null)
            {
                return;
            }

            Light bulb = light.lightToOptimize;
            if (bulb != null)
            {
                bulb.enabled = false;
                if (bulb.gameObject.activeSelf)
                {
                    bulb.gameObject.SetActive(false);
                }
            }

            if (light.fallbackRenderer != null && light.fallbackRenderer.gameObject.activeSelf)
            {
                light.fallbackRenderer.gameObject.SetActive(false);
            }
        }
    }

    /// <summary>
    /// A framework view that re-derives its light from the object being drawn, so the generator can
    /// tell whether the light it is about to bake will actually be per-object.
    /// </summary>
    /// <remarks>
    /// The promise is narrow and it is the whole point: a view carrying this re-applies the light
    /// on every occupy, so the one shared instance behind every object of that behaviour shows each
    /// object its own light. A view added later WITHOUT it would silently give every object of its
    /// behaviour whichever light was baked first, which is the failure this interface exists to
    /// make visible at generation time rather than in somebody's world.
    /// </remarks>
    public interface IDimensionAuthoredLight
    {
        /// <summary>Re-derives this object's light. Called from the view's own occupy.</summary>
        void PointTheLight();
    }
}
